### ISSUE TITLE
Configure workflow to make retina-ready images

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#10]
This is a bit complicated - the double-size idea doesn't quite work perfectly; we should set up a workflow in the build that creates the retina versions, etc, and builds them appropriately.

Basically, it should work that you set the image to the larger size, and then the the workflow turns that image into a retina one and creates a smaller, non-retina one, maybe?

**Comment by bridgetkromhout** [comment]
There are a lot of third-party image resizers out there, if we're faced with needing to build something.

**Comment by mattstratton** [comment]
The resizer isn't the issue. It's a workflow thing, because most workflows assume they get to write the output somewhere else, but we need the images to stay where they are in order to not introduce a gulp/grunt, etc, dependency on local changes, etc.

We cannot resize on the host side because static site :)

**Comment by mattstratton** [comment]
Related to #11

**Comment by mattstratton** [comment]
Fixed in #97
