### ISSUE TITLE
Add social sharing images

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#123]
Should add to frontmatter for where the image is. 

See if we can make a gulp task to auto-build them if they aren't there.

**Comment by mattstratton** [comment]
These images should either be named in a specific way, or put in a certain directory so they can be excluded from the gulp processing.

**Comment by mattstratton** [comment]
OK, this totally works now.

Check it out:

![image](https://cloud.githubusercontent.com/assets/1280666/23084222/eaee95d2-f526-11e6-9139-d47bb135a71b.png)

**Comment by bridgetkromhout** [comment]
Fancy!

**Comment by bridgetkromhout** [comment]
This looks cool. I'm unsure what if anything remains on it, and if anything like an autobuild task is needed, does this need to be in v1.0?

**Comment by mattstratton** [comment]
Autobuild is a huge add, so not for v1. It's already documented in the readme. Closing this one.
