### ISSUE TITLE
Consider changing from Bootstrap to Bourbon/Neat

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#13]
I've been thinking about changing frameworks from Bootstrap to Bourbon/Neat.

Here's some more reading if you want to check it out:

[Bourbon](http://bourbon.io/)- mixin library
[Neat](http://neat.bourbon.io/) - the grid layout tool

I don't think anyone is going to care very much about this but me, since I'm the one who has been using the framework.

The thing that I like about Neat is that it is totally semantic; it's not a lot of `<div>` tags, but rather semantic tags.

I'm going to make a branch in this repo for the example pages I've done so far and see how tough it is in Bourbon and its friends.

**Comment by bridgetkromhout** [comment]
My only opinion is that we need good defaults and examples for people so they don't just write the HTML they're accustomed to. (Looked at the Neat docs and yep, it's different syntax-wise from what people might be used to.)

**Comment by mattstratton** [comment]
Yep. See #18 for a task I have set for this.

**Comment by mattstratton** [comment]
I experimented with this slightly and it's way too much overhead for minimal benefit. Bootstrap has way more stuff out there to work with.
