### ISSUE TITLE
Text alignment of events on homepage is weird

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#134]
See seattle for example

**Comment by bridgetkromhout** [comment]
Although this says Backlog it also is still part of the v1.0 release milestone; I don't really understand if that combination is intentional or leftover. Thanks.

**Comment by mattstratton** [comment]
Label or GH project?

**Comment by bridgetkromhout** [comment]
![screen shot 2017-02-18 at 7 06 41 pm](https://cloud.githubusercontent.com/assets/2104453/23098165/68faeb4c-f60d-11e6-8ce0-9a6afe273b66.png)

My workflow for "what do we still need to do before we release" is to look at https://github.com/devopsdays/devopsdays-theme/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v1.0+Release%22 and I think I am missing something, since there are things in there (like this issue) which seem like we wouldn't block the release on them.

**Comment by mattstratton** [comment]
I'm saying ignore the word "backlog". Use the milestone. This one IS a blocker because I don't feel comfortable releasing with it as is.

**Comment by bridgetkromhout** [comment]
> I'm saying ignore the word "backlog". Use the milestone.

Cool, thanks.

> This one IS a blocker because I don't feel comfortable releasing with it as is.

Okay.

**Comment by bridgetkromhout** [comment]
I noticed that I can't reproduce this problem locally. Maybe that's a clue?

![screen shot 2017-02-18 at 8 55 26 pm](https://cloud.githubusercontent.com/assets/2104453/23098788/d589cf44-f61c-11e6-95d7-2bd5bc770d93.png)

![screen shot 2017-02-18 at 8 55 45 pm](https://cloud.githubusercontent.com/assets/2104453/23098790/da0eec0c-f61c-11e6-9e09-34b90b08fed1.png)

**Comment by bridgetkromhout** [comment]
![screen shot 2017-02-18 at 9 12 06 pm](https://cloud.githubusercontent.com/assets/2104453/23098875/ef0b529c-f61e-11e6-85fa-3662f94e2ea6.png)


I swapped a 300px image out and swapped a 500px image in, and it fixed the mis-alignment. I think this could be related to image sizes.

**Comment by mattstratton** [comment]
Misunderstood which issue this was. This isn't an issue anymore. Closing.

**Comment by mattstratton** [comment]
Oh it still does happen in the dev site. 

Probably due to the image resizing in the workflow? Do you see it in a deploy preview?

**Comment by mattstratton** [comment]
Oh yeah it's totally because Seattle's image is too small. 

We can do some cleverness in the image processing to ensure they are 500px square at least I suppose.

**Comment by bridgetkromhout** [comment]
You're right. I reverted and it's not a problem in the deploy preview:

![screen shot 2017-02-18 at 9 34 25 pm](https://cloud.githubusercontent.com/assets/2104453/23099010/5128c2b8-f622-11e6-934c-0934651eb21b.png)

**Comment by bridgetkromhout** [comment]
> We can do some cleverness in the image processing to ensure they are 500px square at least I suppose.

Seattle (300x300), Raleigh (300x300), and Chicago (300x300) are all below what seems to be the threshold and they appear offset. Amsterdam (354x354) looks fine so the cut-off isn't that much above 300.

Sounds like either you do something in the image processing, and/or we increase the size of these images as a short-term fix, or other...?

**Comment by bridgetkromhout** [comment]
As expected, the larger images band-aid the cosmetic problem without resolving the underlying issue. That is probably our shortest path to not having to fix this before v1.0. Given that we have a workaround, do you still regard this as a v1.0 blocker?

a) Either fixing this goes on the checklist 
or
b) Dropping the larger images in place for those three and running through any others that are available to double-check their size goes on the checklist.

**Comment by mattstratton** [comment]
Fixing the image resizing in gulp is super easy and something I should do prior to v1.0 release.

**Comment by mattstratton** [comment]
This was fixed in #264
