### ISSUE TITLE
Make sponsor layout look pretty

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#137]
There needs to be a nicer demarcation between the levels, and it can all look more delightful.

**Comment by bridgetkromhout** [comment]
The MVP I put in place for this is `<hr>`. It could look better. Perhaps alternating-shade background?

**Comment by bridgetkromhout** [comment]
I don't think we need more than `<hr>` that we now have, for the v1.0 release.

**Comment by mattstratton** [comment]
This is fine :)
