### ISSUE TITLE
events with the same dates don't show on main site sidebar

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#140]
Inspired by https://github.com/devopsdays/devopsdays-web/issues/246 (which applied to the old events page) I gave Ponyville and Hoofington the same dates:

```
Bridgets-MacBook-Air:exampleSite bridget$ git diff
diff --git a/exampleSite/data/events/2017-hoofington.yml b/exampleSite/data/events/2017-hoofington.yml
index f188986..7d45e82 100644
--- a/exampleSite/data/events/2017-hoofington.yml
+++ b/exampleSite/data/events/2017-hoofington.yml
@@ -3,8 +3,8 @@ year: "2017"
 city: "Hoofington"
 friendly: "2017-hoofington"
 status: "current"
-startdate: 2017-01-31
-enddate: 2017-02-01
+startdate: 2017-02-19
+enddate: 2017-02-20
 cfp_date_start: 2016-12-01
 cfp_date_end: 2016-12-30
 cfp_date_announce: 2017-01-01
diff --git a/exampleSite/data/events/2017-ponyville.yml b/exampleSite/data/events/2017-ponyville.yml
index c6c7147..c2a43a5 100644
--- a/exampleSite/data/events/2017-ponyville.yml
+++ b/exampleSite/data/events/2017-ponyville.yml
@@ -3,8 +3,8 @@ year: "2017"
 city: "Ponyville"
 friendly: "2017-ponyville"
 status: "current"
-startdate: 2017-01-29
-enddate: 2017-01-30
+startdate: 2017-02-19
+enddate: 2017-02-20
 cfp_date_start: 2016-12-01
 cfp_date_end: 2016-12-30
 cfp_date_announce: 2017-01-01
Bridgets-MacBook-Air:exampleSite bridget$
```

Here's what happened:

![screen shot 2017-01-30 at 4 17 08 pm](https://cloud.githubusercontent.com/assets/2104453/22444217/a0cf53ce-e707-11e6-839a-d95e2fc7f86c.png)

Contrast with:

![screen shot 2017-01-30 at 4 17 25 pm](https://cloud.githubusercontent.com/assets/2104453/22444227/a7261988-e707-11e6-80fa-80a8df676c6b.png)

**Comment by mattstratton** [comment]
This might have been fixed somewhere else somehow? building it locally I can see both

![image](https://cloud.githubusercontent.com/assets/1280666/22602168/b4fdb1ee-ea07-11e6-9902-eb53ec5d4ae1.png)

**Comment by mattstratton** [comment]
@bridgetkromhout please review

**Comment by bridgetkromhout** [comment]
Yep, it's fixed now. We could dig to see when it got fixed but I'm less concerned about that right now.
