### ISSUE TITLE
Create RSS feeds for events and CFP's

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#15]

**Comment by bridgetkromhout** [comment]
CFPs: the same contents as https://www.devopsdays.org/speaking/
Events: Future and Future Dates TBD from https://www.devopsdays.org/events/

**Comment by mattstratton** [comment]
This feed already exists:

https://www.devopsdays.org/events/index.xml

I need to look at how it is generated and make sure it comes over in the new theme. If I've already done this heavy lifting, it's possible we might be able to consume it similarly for CFP's.

**Comment by mattstratton** [comment]
I still don't really understand how this works, but I think implementing this is quite simple:

we add the following directories:

files into the `section` directory:

`events.rss.xml`
`cfp.rss.xml`

I think that will create the appropriate feeds. That is how I did it in https://github.com/mattstratton/castanet

**Comment by jduv** [comment]
@mattstratton yup.
https://gohugo.io/templates/rss/

**Comment by mattstratton** [comment]
We also need to make sure that there is a CTA button for these feeds on the Events and Speaking pages.
