### ISSUE TITLE
Change from png to jpg for images as much as possible

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#150]
I believe that jpg's are smaller, and we definitely should allow for the ability to use them.

~- [ ] Modify the sponsor files to take an optional parameter of image name~
~- [ ] Modify the sponsor display code to show the optional image name if it is specified~
- [x] Confirm that speakers take a filename and don't try to puzzle it out for the image name

**Comment by mattstratton** [comment]
The downside of using JPG for logos is that it doesn't support transparency. I think that for photos (speakers, etc) they should be JPG.

For example, the apple-jack.png file is 292kb, but as a jpg with 80% quality, it is 109kb.

**Comment by mattstratton** [comment]
Similarly, the ponyville logo-square is about half the size when it is a jpg.

**Comment by bridgetkromhout** [comment]
I made some updates you may want to consider here, @mattstratton - I didn't change ponyville/hoofington though.

**Comment by mattstratton** [comment]
I am pretty sure that I want to keep sponsors the way they are for now; they tend to be small enough images that they aren't a problem, and transparency is helpful.

**Comment by bridgetkromhout** [comment]
> show the optional image name if it is specified

While we're at it, can we add an alt tag for screenreaders?

**Comment by mattstratton** [comment]
Yeah, I've noticed that we have missed a lot of those. I'll fix in #217

**Comment by mattstratton** [comment]
Now that I think I fixed all the alt images, and we are gonna keep sponsors the way they are, I think this can be closed.
