### ISSUE TITLE
Consider processing sponsor image sizes in gulp

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#153]
They're generally pretty small, so we can probably skip them for that processing.

**Comment by mattstratton** [comment]
Thinking about this some more, it might be actually more useful to put special processing on the sponsor images to size them properly - we can then not have to make people put in a specific size, and we can resize them with the responsive thing to the width that we need for each viewport.

**Comment by bridgetkromhout** [comment]
Is this necessary for v1.0?

**Comment by mattstratton** [comment]
Goes with the other image processing fix for homepage. So yep.

**Comment by mattstratton** [comment]
Fixed in #270
