### ISSUE TITLE
Add Travis build step

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#17]
Should crawl all the links in the site now and check for any type of errors, either http status or inside the console

**Comment by bridgetkromhout** [comment]
Won't a lot of old links probably be bad? Do we want to break if some speaker from 2013 deleted their website or something?

**Comment by mattstratton** [comment]
I think my theory is that a bad link is a bug on the site and needs to be fixed. So even if someone did delete something, that's a maintenance task to fix it.

I think that maybe it doesn't go in Travis; there's probably some type of other way we can have the site be crawled for bad links and then turn them into issues to fix. Actually, I think that Google's search console does that for us.

In fact, it does:

![image](https://cloud.githubusercontent.com/assets/1280666/22438147/7a0dc8ea-e6f0-11e6-9cf8-66889892d309.png)

**Comment by mattstratton** [comment]
Not needed.
