### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#18]
I'm not sure if this goes in this repo or the main one, but all the selectors and HOWTO for using the framework (whether it is bootstrap or bourbon/neat) needs to be fully documented.

**Comment by bridgetkromhout** [comment]
Will enough people be using selectors, etc right after go-live that this is a blocker for v1.0?

**Comment by mattstratton** [comment]
This can be moved to v1.1.

**Comment by mattstratton** [comment]
This also includes things that can be done after initial creation - like how to add description frontmatter to pages, sharing images, and how to use extra features.

**Comment by mattstratton** [comment]
The more I think about it, this is more about documentation for developers of the theme itself, as hopefully it won't just be the two of us contributing all the time.

**Comment by mattstratton** [comment]
This needs some of the following updates:

- our workflow for feature requests (it's outdated)
- specifics about the scss includes

**Comment by mattstratton** [comment]
Very close to "done"; just should probably point out that we use bootstrap v4.
