### ISSUE TITLE
Create workflow for updated exampleSite in this theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#180]
We need a mechanism for keeping date, content, and static files from `devopsdays-web` over here for regression testing.

I'm thinking of a workflow that goes like this:

`git pull` from `devopsdays-web` -> check out a `sync-files` branch in a local copy of `devopsdays-theme` -> rsync a bunch of stuff to a local `devopsdays-theme` -> commit those changes locally -> submit a PR to this repo.

I already do this "manually"; the theory is I can have this set up to run on my little t1 micro workstation that's always running in AWS as a cron job once a day or so. 

@bridgetkromhout had some theories about clearing out old unnecessary stuff too.

This is my current shell script for just the `rsync`:

```
rsync -rv --update --exclude=.git /Users/mattstratton/src/github.com/devopsdays/devopsdays-web/content/ /Users/mattstratton/src/github.com/devopsdays/devopsdays-theme/exampleSite/content/
rsync -rv --update --exclude=.git /Users/mattstratton/src/github.com/devopsdays/devopsdays-web/static/ /Users/mattstratton/src/github.com/devopsdays/devopsdays-theme/exampleSite/static/
rsync -rv --update --exclude=.git /Users/mattstratton/src/github.com/devopsdays/devopsdays-web/data/ /Users/mattstratton/src/github.com/devopsdays/devopsdays-theme/exampleSite/data/
```

**Comment by bridgetkromhout** [comment]
Here's my `rsync`: 
```
devopsdayspath="/Users/bridget/github/devopsdays/"
for foo in data static content; do rsync -avz --delete --update --exclude=.git --exclude=.gitkeep --exclude=*ponyville* --exclude=*hoofington* $devopsdayspath/devopsdays-web/$foo/ $devopsdayspath/devopsdays-theme/exampleSite/$foo/;done
```

**Comment by bridgetkromhout** [comment]
I'm leaving off `--exclude=events.md --exclude=speaking.md` because having --update means we don't have to worry about them for now, but I renamed partials which is where there's inconsistency there.

**Comment by bridgetkromhout** [comment]
Do we want to exclude https://github.com/devopsdays/devopsdays-theme/blob/master/exampleSite/static/robots.txt from updates because the dev site starts with dev not www?

**Comment by mattstratton** [comment]
Oh yeah.

**Comment by mattstratton** [comment]
Omg yeah I didn't look at how you did this before. Only content directory. There's a bunch of shit outside the content directory in the old way that we don't want anymore.

**Comment by mattstratton** [comment]
I meant content, data, and static. But not theme-based static.

**Comment by mattstratton** [comment]
All the shortcodes which used to live outside of the theme should have already been moved inside the theme I think.

**Comment by mattstratton** [comment]
Never mind. I'm stupid.

**Comment by mattstratton** [comment]
I think all we really need to sync are
content/events/*
data/*
static/* (excluding robots.txt)

**Comment by mattstratton** [comment]
No longer needed due to consolidated repos
