### ISSUE TITLE
Create simple "Here's what an event needs" doc

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#181]
This will be a rough markdown file that structures the data file fields needed, the files needed, what the data things do, blah blah blah.

Should go in a `/docs` folder of the theme.

**Comment by mattstratton** [comment]
Connected to #18

**Comment by bridgetkromhout** [comment]
Given how much a pain it is to construct everything correctly, I don't think we should maintain a separate "how to build your event by hand" document. I think the source of truth should be the utilities scripts; bash is close enough to English that someone can just consult those and then do it by hand if they prefer.

**Comment by mattstratton** [comment]
Except for folks who use Windows. That's a thing.

**Comment by bridgetkromhout** [comment]
We had at lease one person using these scripts on Windows, didn't we? I want to make sure we don't end up with two sources of truth.

**Comment by mattstratton** [comment]
I think this is actually covered in the README in the Utilities directory, now that I've actually looked at it :)
