### ISSUE TITLE
Refactor event nav on small devices

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#185]
The collapse model a) doesn't work and b) looks stupid.

Need to figure out how this stuff should properly look.

**Comment by bridgetkromhout** [comment]
If you happen to have either a screencap or a text description of what looked stupid, it would help to know more. For when we inevitably forget. :)

**Comment by mattstratton** [comment]
It looks like this:

![image](https://cloud.githubusercontent.com/assets/1280666/23001918/5651065a-f3ad-11e6-8fb5-77f328f567bb.png)

**Comment by bridgetkromhout** [comment]
Is this a blocker for the v1.0 release?

**Comment by mattstratton** [comment]
I think so.
