### ISSUE TITLE
Provide a robots.txt

### ISSUE THREAD

**Issue by tgross** [devopsdays/devopsdays-theme#210]
The site doesn't have a robots.txt file, which means that Google is indexing https://dev.devopsdays.org/robots.txt (as I discovered by fat-fingering the URL).

I'm not sure whether the build/deploy setup supports having a separate robots.txt for dev vs prod, or whether prod needs to have a robots.txt for any miscellaneous files that shouldn't be indexed.

**Comment by bridgetkromhout** [comment]
Thanks, Tim! We'll figure it out. For "Stratton" values of "we". ;)
