### ISSUE TITLE
Add privacy policy to footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#218]
It's a shortcode called `privacy_policy.html`; I don't recall why I made it a shortcode and not a partial before, but there must have been a reason.

**Comment by mattstratton** [comment]
Aha. Because it's used by the `privacy.md` content page. Which already exists and we don't need to do anything with it. 

But we need to add a link to it somewhere still.

**Comment by bridgetkromhout** [comment]
In the old theme it's linked in the footer. We probably need to make sure we still link to anything we care about from the footer.

**Comment by mattstratton** [comment]
Yeah, the overall footer content needs to be decided upon.

**Comment by bridgetkromhout** [comment]
Related: https://github.com/devopsdays/devopsdays-theme/issues/141

**Comment by bridgetkromhout** [comment]
> Yeah, the overall footer content needs to be decided upon.

I'm fine with keeping the same content as now, for the v1.0 release, and then thinking it over more - what would you prefer?

**Comment by mattstratton** [comment]
How about similar content but include the twitter feed?

**Comment by bridgetkromhout** [comment]
Sure, fine by me.
