### ISSUE TITLE
Refactor frontpage image logic to use path separator key

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#22]

**Comment by mattstratton** [comment]
This might not be needed, as the appveyor tests are passing. This just needs to be tested. I'll try to build this on a Windows machine and see if it works.

**Comment by bridgetkromhout** [comment]
Do we still need this for the v1.0 release?

**Comment by mattstratton** [comment]
I haven't tested it yet, but given we work on Windows today we can't introduce a regression.

**Comment by mattstratton** [comment]
The main test is going to be for me to just fire this up on my Windows machine, which shouldn't take too long. I'll do a regression test tonight without setting pathseperator at all; maybe it's not needed anymore.

**Comment by mattstratton** [comment]
OK, we still need the pathseperator (however we spell it), but not on the home page, so this issue can be closed.
