### ISSUE TITLE
Make dates in left navbar browser-driven

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#221]
The content that is displayed is dependent upon a build of the site; so in theory, an event could be over, but if we don't do a deploy, it will still show up.

Ideally this should be javascript driven based upon the browser's date. This is a future enhancement.

**Comment by bridgetkromhout** [comment]
Ah, sure. I see this as not a major issue since chances are, someone's going to update something pretty soon anyhow (whether for that event or another).

**Comment by mattstratton** [comment]
Hence 2.0 :)

**Comment by mattstratton** [comment]
I don't think we need this. It would solve the event ordering problem with builds though :)

![](https://media1.giphy.com/media/amxLHEPgGDCKs/giphy.gif?cid=e1bb72ff5b8f2ed62e6c516b4959038b)
