### ISSUE TITLE
debug facebook OG tags

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#246]
We're publishing some unnecessary tags on the non-blog pages (actually, we aren't publishing them properly on the blog posts at all) so this should be investigated.

**Comment by bridgetkromhout** [comment]
Is this a blocker for v1.0? Thanks.

**Comment by mattstratton** [comment]
Move it to v1.1

**Comment by mattstratton** [comment]
The only real issue I've seen is a suggestion to specify the dimensions of the sharing image, but that's tricky.

```
Use og:image:width and og:image:height Open Graph tags
```
Everything else is passing without errors/warnings on the facebook debugger, so this is resolved!
