### ISSUE TITLE
Fix aspect ratio issue on local event contact page

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#266]
We aren't constraining the aspect ratio for the images: 
![screen shot 2017-02-20 at 1 15 11 pm](https://cloud.githubusercontent.com/assets/2104453/23138735/aab2cb4c-f76e-11e6-95cd-1183a41fb905.png)

**Comment by mattstratton** [comment]
Yep. that's because, well, that's how card work in bootstrap.

They smush until they collapse.

**Comment by mattstratton** [comment]
We can probably experiment with what the size dimensions work best for it.

**Comment by mattstratton** [comment]
Could also just dump using the cards and use the same type of layout as we did for speakers, although I suspect they will act up.

**Comment by mattstratton** [comment]
Need to look at the gulp image processing

**Comment by mattstratton** [comment]
Fixed in #268

**Comment by clebio** [comment]
Is this deployed? The aspect ratio appears wrong, in the other direction, to me right now.
https://dev.devopsdays.org/events/2017-ponyville/contact
<img width="1193" alt="screen shot 2017-02-25 at 8 50 33 am" src="https://cloud.githubusercontent.com/assets/811175/23332043/74f5a14c-fb37-11e6-89fa-1654fe0d80a3.png">

**Comment by mattstratton** [comment]
@clebio what browser and screen size? We fixed this along with some other stuff a while ago (I've since put in a fix that handled ie11; that might have caused weirdness for you)

**Comment by clebio** [comment]
@mattstratton macbook pro scaled more space ("looks like 1920 x 1200); Chrome Version 56.0.2924.87

**Comment by mattstratton** [comment]
OK, so something responsive is not happening here, because when I rescale, they get smaller, but they don't clear when I change.

I'm going to reopen this issue to chase it down, although it seemed to work fine when I set my screen size to approximately that size (OS X, but on super large external monitor as my 13" MBPr won't get that big). I'll dig.

**Comment by mattstratton** [comment]
I'm thinking my fixnis going to be constraining the organizer images to a specific ratio and resizing them in the gulp task. I think setting `height: auto` is what is messing us up.

**Comment by mattstratton** [comment]
@clebio I think that this has been fixed - can you test it for me?

**Comment by clebio** [comment]
Yes, looks good on my end! @mattstratton 👍

**Comment by mattstratton** [comment]
Fixed in #331
