### ISSUE TITLE
Auto-detect for sharing image and show default if not there

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#286]
Right now, no image is set in open graph tags on event pages if the `sharing.jpg` isn't set. We could use some of the same logic as used on the homepage to detect the image, and display the default sharing one if it's not found.

**Comment by bridgetkromhout** [comment]
Ah, this answers one of my questions. Thanks.

**Comment by mattstratton** [comment]
This was fixed in e4e3d0135408f695a979c15f6dc6ec8fa11622e8
