### ISSUE TITLE
contacts all squashed together in IE11 on new theme

### ISSUE THREAD

**Issue by MikeRosTX** [devopsdays/devopsdays-theme#300]
### Expected behavior
To be displayed and look just fine as it does in Chrome.

### Actual behavior.
List of contacts are all squashed together in IE 11. Have not yet tested newer versions of IE. See attachment.
![squashed_contacts](https://cloud.githubusercontent.com/assets/11631454/23234327/54b7d4b2-f917-11e6-849d-4bcaf4579689.jpg)

### Steps to reproduce the problem.
No steps to repro, just browse the page.

### Operating System and Version
OS Name	- Microsoft Windows 8.1 Enterprise

### Web Browser and Version
Internet Explorer 11 (Version 11.0.9600.18538)
Update Versions: 11.0.38 (KB3203621)

**Comment by mattstratton** [comment]
Hmm. This works with Edge, but not IE. Just something I observed on my Win 10 Surface.
