### ISSUE TITLE
Past events line in the sidebar makes no sense

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#308]
The events sidebar says "past events" at the bottom, but it doesn't link to anything. 

Should this link to the /events page, or should we just get rid of it?

### Reproduction steps:
Open the page. Look at the bottom of the sidebar.

**Comment by bridgetkromhout** [comment]
When I view source or hover over it with Chrome I see the link. I'm confused about what you're seeing.

![screen shot 2017-02-23 at 3 16 30 pm](https://cloud.githubusercontent.com/assets/2104453/23277272/36121fd0-f9db-11e6-951e-b2438e90b87a.png)

![screen shot 2017-02-23 at 3 14 07 pm](https://cloud.githubusercontent.com/assets/2104453/23277143/dea3e2e2-f9da-11e6-9056-e314a2244e7b.png)

**Comment by mattstratton** [comment]
I swear it didn't work when I looked before. But you're totally right. I blame myself.
