### ISSUE TITLE
Suggestion on sponsor images size being displayed

### ISSUE THREAD

**Issue by MikeRosTX** [devopsdays/devopsdays-theme#310]
### Expected behavior
Appearance of sponsor logos to be of a more moderate size when displayed to avoid taking up a lot of real estate and look overwhelming.

### Actual behavior
Some sponsor logos are going to be bigger than others.

### Suggestion
1. Either make all logos the same size of 100x100. (preferred)
2. An alternative if you want to make it distinguishable by levels, start at the very bottom level at 100x100 and increase them x50 each level.

EX:
PLATINUM - 300x300
GOLD - 250x250
SILVER - 200x200
BRONZE - 150x150
MEDIA / COMMUNITY - 100x100

**Comment by mattstratton** [comment]
The sponsor logos all have the same width, or at least they are supposed to. All images in the sponsor directory are resized in the build pipeline.

**Comment by mattstratton** [comment]
We made them 200x200 for display based upon other feedback, but it's trivial to make the size smaller.

**Comment by mattstratton** [comment]
We will no longer enforce square logos due to issues with sponsors whose logos aren't square, which tend to result in non-optimal logo appearance (letterboxing)

**Comment by mattstratton** [comment]
@mikerostx - what are your thoughts on the resized layout now? Better?

**Comment by mattstratton** [comment]
More details in https://github.com/devopsdays/devopsdays-theme/pull/350

**Comment by MikeRosTX** [comment]
Definitely like it much better. Feel free to close this one.
