### ISSUE TITLE
Move gulp tasks into a separate repo

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#317]
In theory, this makes repurposing them across the projects easier.

**Comment by mattstratton** [comment]
This would require doing some submodule magic.

**Comment by bridgetkromhout** [comment]
> submodule magic.

:delicate_shudder:

**Comment by mattstratton** [comment]
Eh. Nobody has to deal with this one but me.

**Comment by bridgetkromhout** [comment]
Is this still being considered?

**Comment by mattstratton** [comment]
I think that it is - now that I think about it, I think instead of submodules, we would be able to roll the tasks up into an npm module that each repo would just install itself. 

I wouldn't close this out yet - I want to investigate.

Connected to #507

**Comment by bridgetkromhout** [comment]
Question: should we resolve this as `WONTFIX` due to the desire to combine repos?
