### ISSUE TITLE
Standardize input image sizes 

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#318]
Since we control resizing in the build, we should be able to make it easier by having all square images come in at the same size. 

All square images (homepage logo and organizer bio) should come in as 600px square jpg.

**Comment by mattstratton** [comment]
Speaker images will be slightly trickier because of backwards compatibility.

**Comment by mattstratton** [comment]
Related to #266

**Comment by bridgetkromhout** [comment]
> All square images (homepage logo and organizer bio) should come in as 600px square jpg.

I think it's unrealistic to assume this is going to happen. In particular, to make the logo-squares I dropped non-square images onto a white background and re-cropped in some cases. But as they weren't already 600px in almost all cases, we'd be blowing up 300px images if we wanted to create the new required size.

**Comment by mattstratton** [comment]
We recommend 600 x 600, but 300 x 300 minimum. TBH, anything less than that will look like shit.

**Comment by mattstratton** [comment]
And we DO blow up 300 x 300 images to retinafy them, but it doesn't make them look bad because, well, how retina works.

My point here was to say instead of "make your homepage square 250 x 250, and your organizer image 300 x 300, etc", since they are all square anyway, just say "they need to be square, with a minimum of 300 x 300 px, but 600px x 600px is recommended".

**Comment by bridgetkromhout** [comment]
Okay. re: the looking-like-shit thing, do we need a separate task where we follow up with anyone whose images are too small?

**Comment by mattstratton** [comment]
If they are smaller than 300x300 they'll look like total crap. Forget about the resize.

**Comment by mattstratton** [comment]
I mean seriously, 300x300 is not that big.

**Comment by bridgetkromhout** [comment]
Sure. I know you did some image resizing stuff to fix some bad icon-squares so I will leave it to you to decide if that's good enough or if we reach out to anyone about their small images.
