### ISSUE TITLE
Style tweaks

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#319]
*from designer*

Global:

- [x] Sub nav should be left-justified with the DevOpsDays brain logo.

- [x] Vertical white space between global nav, sub nav is stellar. The distance between the sub nav and text header should be the same as this (my count is 63 px.)

Page footer

I’m amenable to a page rule if you think it is necessary, but this one is very heavy. Trimming it from 10 px high to 5 px will allow it to work better with the blue section headers beneath (essentially the rule is the width of the letter stroke, if that makes sense).

- [x] Trim page rule

/events
- [ ] Space between photo and date looks good (14 px). This should be equal between date and city. 

/blog

- [x] Align ‘Blog’ with ‘2017’ (add 43 px white space).

/sponsor

because it’s aligned horizontally with ‘past events’, the alignment here works.

/speaking

- [ ] horizontal alignment is good here as well, but if the thin rule above ‘city/CFP closes/event starts’ could be taken out and the rest of the rules be the thin size, that’d be swell.

/organizing

Looks great.

/events/program/

I had designed these as white text over color blocks to denote the different days. If all white tested better I am amenable, but I’d prefer to eliminate the bordered boxes with light gray stripe at the top in favor of a 2px horizontal blue rule between the two days (and just white space between the sub nav and the date at the top and at the bottom between the timetable and ‘ignite sessions’)

- [x] Improve styling on program page ^^^

- [x] add white space between day 2 block and ignite sessions (total 16 px, equal to that of ‘ignite sessions’ and the day/date)

**Comment by bridgetkromhout** [comment]
> Align ‘Blog’ with ‘2017’ (add 43 px white space).

Assuming you agree with https://github.com/devopsdays/devopsdays-theme/pull/329 that will fix this issue.

**Comment by bridgetkromhout** [comment]
Hey @mattstratton, it's not entirely clear to me what is definitely still going to be happening for this issue for 1.0 - please update it if you have insights. Thanks!

**Comment by mattstratton** [comment]
I think this is good for now. Let's pop it to Next Steps.

**Comment by mattstratton** [comment]
Thisis probably pretty well done.
