### ISSUE TITLE
Calm the bot down about case

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#324]
### Expected behavior

Leave people alone about uppercase both because it doesn't matter, and because if they're starting with an error message or something, forcing a false uppercase letter is weird.

### Actual behavior

![screen shot 2017-02-25 at 3 40 27 pm](https://cloud.githubusercontent.com/assets/2104453/23334995/f36f31bc-fb70-11e6-82b5-0bb62233fe94.png)

### Reproduction Steps

Create a new issue with a lowercase letter to start the title

**Comment by mattstratton** [comment]
The rules are set in `contributing.json` so if you don't want to wait for me, you can fix it yourself :)

**Comment by bridgetkromhout** [comment]
Hah. Okay, I will. I figured you picked the rules you wanted. :)
