### ISSUE TITLE
Retry failed Appveyor builds

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#325]
### Expected behavior

I'd like it if Appveyor would retry instead of fail when there is an intermittent error like a git clone hanging up unexpectedly. 

### Actual behavior

The current behavior puts a failing check on the pull request (even though, as far as I can tell, the pull request has nothing I can correct):

![screen shot 2017-02-25 at 3 44 51 pm](https://cloud.githubusercontent.com/assets/2104453/23335029/841fa89a-fb71-11e6-8451-0575617ec1dc.png)

### Reproduction Steps

Unsure how to produce on demand. You can see an example on: https://github.com/devopsdays/devopsdays-theme/pull/322

**Comment by mattstratton** [comment]
I have no idea if any of the build systems (Travis, etc) will allow for this. We have seen this happen in prod in Travis a lot.

**Comment by mattstratton** [comment]
To the best of my knowledge, this isn't something we can configure.
