### ISSUE TITLE
improve readability of future events sidebar

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#335]
### Expected behavior

I'd like the event sidebar to be more readable, so I'm trying to make the list of dates less cluttered and easier to read.

### Actual behavior

Right now, a month is repeated twice on the same line even if the month doesn't change. Also, a colon might enhance readability.

### Reproduction Steps

Left: the current setup. Right: my proposed edit.

![screen shot 2017-02-26 at 9 07 16 pm](https://cloud.githubusercontent.com/assets/2104453/23347457/1f10e354-fc68-11e6-9112-4c4ec7f6062e.png)

I made a PR (https://github.com/devopsdays/devopsdays-theme/pull/334) for this but I'm closing it after talking with @mattstratton since we're so close to a release. We can discuss this later when it won't confuse people checking pre-release.

**Comment by mattstratton** [comment]
Tracking dev ticket in #424

**Comment by bridgetkromhout** [comment]
Hey Matt, just so I understand the workflow - what was the motivating need for you to migrate the content of this issue into a seemingly very similar issue? Thanks.

**Comment by mattstratton** [comment]
Because there isn't a direct hook between issues in gh and ideas in prodpad. So when I said an idea which was being tracked in prodpad was pushed to Dev, it created a new one. 

Maybe not ideal.

**Comment by mattstratton** [comment]
The motivating issue is that most new enhancements shouldn't start out as GH issues, but there were a few so there is going to be some duplication for a while.

**Comment by bridgetkromhout** [comment]
Thanks for filling me in.
