### ISSUE TITLE
Fix gap on Ignite sessions

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#336]
### Expected behavior
There should be a gap between "Ignite Sessions" and the program listed above.

### Reproduction Steps

Visit https://dev.devopsdays.org/events/2017-ponyville/program/

### Fix steps:
Modify the '`h3' tag on "Ignite Sessions" to include a `margin-top:8px;`

Connected to #319

**Comment by bridgetkromhout** [comment]
While you're editing the layout of the ignites, can you take a quick look at how narrow the columns are? 
![screen shot 2017-02-27 at 10 48 57 am](https://cloud.githubusercontent.com/assets/2104453/23370486/72f853c2-fcda-11e6-9013-b6320ab22b43.png)

I look at that and see a lot of whitespace and a lot of text wrapping when it doesn't seem like it needs to.

**Comment by bridgetkromhout** [comment]
Better reference screenshot with more context

![screen shot 2017-02-27 at 10 55 23 am](https://cloud.githubusercontent.com/assets/2104453/23370749/5374590a-fcdb-11e6-8bed-b52d1d533a29.png)

**Comment by mattstratton** [comment]
Making a note to myself here - we should maybe add some special styling for Ignites or open space elements in the data file - ignites could be clickable to an anchor tag lower on the page to the ignite section too.

This should be a separate issue but I'm recording it so I don't forget.
