### ISSUE TITLE
Alignment tweaks to navbars

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#344]
The global navbar is slightly indented to the right from the event navbar; it should be the opposite.

To reproduce: Take a look at any event-level page and compare the brain logo the event name.

Please also check this on various screen sizes.

**Comment by bridgetkromhout** [comment]
![screen shot 2017-02-27 at 1 07 10 pm](https://cloud.githubusercontent.com/assets/2104453/23375690/dceb5a72-fcee-11e6-99bf-4e29fc667bf1.png)
