### ISSUE TITLE
Add support for background header image to event page

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#35]
If this is set, then it should display as the background. If it is not set, then it should not have a background image.

![devops_type_color_all5_pdf__page_3_of_5_](https://cloud.githubusercontent.com/assets/1280666/20927773/a8d7fbde-bb88-11e6-9861-0e26af9697b1.png)

**Comment by bridgetkromhout** [comment]
I think we discussed this elsewhere, but my main concern here is text that won't be readable atop arbitrary pictures (unless said text comes with its own contrasting background bar).

**Comment by mattstratton** [comment]
I see this as a totally opt-in feature, so if it works, it works.

It just looks nice to have more images. There might be a way to put the contrasting background in there. I don't think we kill this feature just yet; let me try it out.

**Comment by mattstratton** [comment]
Pushing this off to a later release; it's not important right now.

**Comment by mattstratton** [comment]
Note: this will require special handling of the CTA buttons/share buttons, as they are transparent.

**Comment by mattstratton** [comment]
Duplicate of #449, and this has been added.
