### ISSUE TITLE
Add badges to events that have open CFP or registration

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#374]
Not sure where this badge would show up, but it would be nifty

**Comment by bridgetkromhout** [comment]
The only place I could see this being visually useful is on the main page, since presumably people already edit their own site to say what they want? But that sounds like it could be visually cluttered.

**Comment by mattstratton** [comment]
I'm probably not explaining what I mean by a badge well; it would just be a little badge in the corner of the logo on the main page, which is what I meant but didn't describe properly.

**Comment by bridgetkromhout** [comment]
I don't like the idea of messing with the appearance of people's logos, so much - we already have the URL that is basically "CFPs that are open". Do we really think people are looking for one where reg is open, without caring where it is? Basically I'm not seeing the use case for that.

**Comment by mattstratton** [comment]
Yeah, I was just getting. UI-happy.
