### ISSUE TITLE
Seed this forum with your ideas

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#376]
via UserVoice Team:

UserVoice pro tip #1: 
Your customers are full of ideas, but people are more likely to contribute if they're not among the first. Add your own ideas now!

View on UserVoice: http://devopsdays-website.uservoice.com/forums/595393-general/suggestions/18549997-seed-this-forum-with-your-ideas

**Comment by MikeRosTX** [comment]
We used UserVoice at Microsoft internally and externally to get continuous feedback on improving beta and future features. It's a great tool. Will there be a link to it from **CONTRIBUTING.md**?

**Comment by mattstratton** [comment]
Considering that uservoice costs about a billion dollars, probably not. I'm experimenting with some cheaper/free tools.

**Comment by mattstratton** [comment]
The WIP for feature requests right now can be seen in the README of this repo, if you scroll down. 

I'm playing around with this: http://devopsdays.helprace.com/
