### ISSUE TITLE
Follow-up on #300 squished images in IE11

### ISSUE THREAD

**Issue by MikeRosTX** [devopsdays/devopsdays-theme#379]
### Expected behavior
Using 600x600 jpg images and would like them to display in IE11 as the do in Chrome.
Might need to use 300x300 jpg images to properly get them displayed in both browsers.
![chrome](https://cloud.githubusercontent.com/assets/11631454/23885719/152a206c-0843-11e7-87fe-b744cfa0dd54.jpg)

### Actual behavior
In IE11 they kind of look as squished up. Not as in #300, but not acceptable.  
![ie11](https://cloud.githubusercontent.com/assets/11631454/23885691/e5857c44-0842-11e7-8c83-d36c2ae57197.jpg)

### Operating System and Version
Same as in #300,
### Web Browser and Version
Same as in #300.

### Next Step
Will add a comment once I change images to 300x300.

**Comment by MikeRosTX** [comment]
### Steps Completed
Images were changed to 300x300 in [#1994](https://github.com/devopsdays/devopsdays-web/pull/1994) and they images are acceptable in IE11 and Chrome.  I'm sure they look fine in Firefox, but don't have this browser installed to actually know.

Not sure it this is worth mucking with it now so close to RTM or just simply change the Readme and mess with the 600xx600 image size at a later date.

**Comment by mattstratton** [comment]
If they were pushed through the full prod workflow, they'd be fine (they are resized for retina to various sizes but you won't see that until it's built to master and only after 3/15's build pipeline)

**Comment by mattstratton** [comment]
Can you try http://test.devopsdays.org/events/2017-chicago/contact/ in IE11? This is what they will look like when fully processed (the source images are a mix of 300x300 and 600x600; they get created for retina during the merge to master portion).

I tested it on IE11 on my Surface, and they seem fine.

**Comment by mattstratton** [comment]
@MikeRosTX I believe that this works as designed?

**Comment by mattstratton** [comment]
I'm going to close this one out as I believe it works as designed. Please feel free to re-open the issue if you disagree :)
