### ISSUE TITLE
Determine if program days should be fully collapsable

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#38]
http://jqueryui.com/accordion/#collapsible for more details.

Currently, one of the days is always open. Should we allow for both to be collapsed? Not sure.

**Comment by bridgetkromhout** [comment]
I'm not sure if this matters as much as "default should be open to current day" if looked at on the second day (no idea how feasible this is).

**Comment by mattstratton** [comment]
Oh, well that's slightly tricky but not super hard. Just some extra javascript madness (to make it auto-expand the second day if that date is the same as current date).

**Comment by bridgetkromhout** [comment]
MVP in my mind is all-expanded. I don't think "collapse of non-active day" is important in relation to anything else we want to accomplish.

**Comment by mattstratton** [comment]
I think we allow for both to be collapsed, and default to both expanded.
