### ISSUE TITLE
Create backwards compatibility for old-style talks

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#4]
The intent is to move as much of the speaker/talk data into frontmatter on the talk page, which removes the need of the data files for the speakers.

However, in the interests of not having to retcon all the old stuff, we need to add a check to see if the talk was built with the old style.

Without knowing exactly how the new style is going to work, I think we would do something like this:

1. Check if the new-style frontmatter exists (there are probably some fields that the old one doesn't use anymore, for example, `bio`)
2. If the new-style frontmatter doesn't exist, try to find a datafile for the speaker and use that to populate the fields
3. If no datafile exists, then we throw an error.

**Comment by mattstratton** [comment]
To raise an additional question - is there value in moving the speaker/talk data into the frontmatter? My thought was that in the current implementation, there are two files that need to be created for each talk:

`rainbow-dash.md` and `rainbow-dash.yml`

The `.md` file contains basically just the abstract. All the other information is in the datafile. I think that everything in the datafile could be obtained in frontmatter of the talk page, i.e., a construct like this:

```
+++
name: "AJ Bowen"
City = "Minneapolis"
Year = "2016"
date = "2016-07-15T22:06:24-06:00"
title = "Your Meetings Are Unbearable: Cheat Codes From Occupy"
type = "talk"
talk_date = "2016-07-04"
talk_start_time = "08:00"
talk_end_time = "08:45"
twitter = "s0ulshake"
bio_pic = "ajbown.jpg"
bio = "AJ Bowen is on a mission to containerize all the things and help others to do the same. In the past, AJ has done technical support, evangelism, and customer and developer advocacy at Gandi. Her other experience includes heavy involvement in the Occupy movement in Kansas City, where she discovered the delightful and complicated world of horizontal organization in groups of passionate people with wildly diverse political perspectives, and humanitarian work in Haiti. AJ doesn’t like being told what to do—or telling others what to do—and is on a constant mission to eliminate unnecessary hierarchy."
youtube = "emGKB8TABvI"
vimeo = ""
speakerdeck = "https://speakerdeck.com/mattstratton/shifting-left-securely"
slideshare = "http://www.slideshare.net/mattstratton/the-five-love-languages-of-devops-54549536"
slides = ""
+++
Most work meetings are full of interruptions, repetitions and microaggressions. To make matters worse, they always seem to drag on forever.  At Occupy, ain't nobody got time for that, so we adapted time-tested anarchist techniques and came up with a simple, efficient horizontal decision-making process.  I would like to show you the hand gestures that go with these techniques; these alone are guaranteed to cut your meeting times in half and save 72% of your sanity.
```

Here's what those fields do:

* `title` - obviously, the title of the talk
* `type` - is this a "talk" or an "ignite" (used by the program generation logic)
* `talk_date` - optional field; but required by the program generation logic
* `talk_start_time` optional field, but required by the program generation logic
* `talk_end_time` optional field, but required by the program generation logic
* `bio_pic` Field to define the picture to use, relative to `static/events/YYYY-CITY/speakers/`  If not set or not present, will default to `static/events/YYYY-CITY/speakers/`. If not set, will display default headshot (need to clarify this via #7)
* `bio` the Markdown-enabled bio of the speaker. Quotes must be escaped (we have this constraint in the datafiles today anyway)
* `youtube` The youtube ID for the video for the talk. Optional. If set, the talk page will show this youtube video as an embed.
* `vimeo` Similar to Youtube, but probably the full url to the Vimeo video. I don't know enough about Vimeo.
* `speakerdeck` The URL to the slides on Speakerdeck. Optional. Will embed the slides.
* `slideshare` The URL to the slides on Slideshare. Optional. Will embed the slides.
* `slides` The URL to where the slides can be displayed. Optional. Will simply display a link to them.

**Comment by bridgetkromhout** [comment]
Hmmmm. Okay so I see a problem. At some events, a speaker has two "things" (like a talk and an Ignite, or a talk and a panel). So the model of tightly coupling "speaker identity" (name, twitter handle, picture, bio) with "thing they are doing at this conf" isn't going to work well with what you're showing here.

**Comment by bridgetkromhout** [comment]
> The intent is to move as much of the speaker/talk data into frontmatter on the talk page, which removes the need of the data files for the speakers.

Specifically, I think this is an incorrect assumption which will lead to results that won't work well.

**Comment by mattstratton** [comment]
OK, so then we move all the "speaker" specific stuff into the data file, and the "talk" specific file stays with the talk. I didn't think about the "speaker might be used in more than one place in an event" use case. 

My main point of moving stuff out of `yaml` as much as possible is that `yaml` is so picky about formatting. But it hasn't really been a problem yet.

So how about this:

The `speakername.yml` includes things like name, twitter, bio, bio_pic, etc.
the `talkname.md` includes things like abstract (probably the main content actually, not a frontmatter field), plus optional fields like start time, talk date, youtube, etc.

**Comment by mattstratton** [comment]
If we are going down this path (which I support), what should the behavior be on the home page of an event? It's going to display thumbnails of the speakers, but if I speaker has two talks...not quite sure how to handle what it should link it. Just the first talk? OR...we can have a "speaker page" template, which just displays the speaker's name, etc, and if you click on it, that takes you to the speaker page which would have links to the talk(s) for that even with that speaker.

That's a lot of clicks, though. It's a tough one to solve for because a "default" behavior is challenging. Like, I might assume that it should just be the first talk of type "talk" that is returned, but maybe the event wants to override?

Maybe we could have an optional, override parameter in the datafile which is "talk to link to", which is what would be returned if it is there. I think the "person is involved in more than one talk" at the event is enough of an edge case that we should handle for it, but we don't have to try to predict behavior as long as we provide an override.

**Comment by mattstratton** [comment]
Thinking this through some more; multi-speaker talks are going to present a similar issue.

So I think what happens is that the event home page displays all the TALKS...and there is an optional frontmatter for the `talkname.md` that specifies the thumbnail to use (otherwise it will use the one for the bio of the speaker attached to it, and if there are multiple speakers, it will just use the first one listed). 

Similarly, the frontmatter of a talk needs to take `speakers` as an array (similar to how we do "guests" on ADO), so it can display all of them on the talk page.

**Comment by bridgetkromhout** [comment]
> (otherwise it will use the one for the bio of the speaker attached to it, and if there are multiple speakers, it will just use the first one listed).

Either the event home page is telling you about speakers (in which case you need to list them all for obvious reasons like a realistic picture of the diversity and treating all speakers as equal with their co-speakers), or the event home page is telling you about stuff that will happen at the event (in which case using speaker headshots is a weird choice anyhow - since plenty of things on the schedule aren't specific to a speaker), or some other option we haven't considered (like not putting that much onto the front page? :trollface: )

**Comment by mattstratton** [comment]
Let's take a step away from the homepage question and simply say "if I'm showing a list of speakers, which talk should it point to?"

The display of stuff on the homepage isn't, like, the "program" so to speak; I think the design approach was to invite interest by giving a nice visual of some of the content. As I mentioned before, I also think this can be a feature-toggle. 

But we do need a speaker page, regardless, which will list all the speakers and should link to their talks. I am very in favor of the "grid of headshots" to display this, so having a boring `<li>` element that bullet lists the talks under their name isn't super delightful. Hmmm.

**Comment by bridgetkromhout** [comment]
> if I'm showing a list of speakers, which talk should it point to?

A speaker's headshot should point to a speaker page containing headshot, bio, and links to or inlines of all their relevant content they're participating in. The speaker page just catting together all their stuff is fine by me - it's nice for them to just have one page - i don't care if, say, a panel appears on my page, and also your page, as long as both are a clickable link to the panel page. The content needs its own separate identity for cases with multiple speakers.

We've been kinda handwavey with the data model because we could get away with it, but i hate the multi-speaker hack I came up with.

we actually need a link that goes to a human, and a link that goes to a piece of content, if we want to be able to have arbitrary mappings between them. the default destination of the "piece of content" link could be the speaker page if you want as little clicking as possible and that's our most common use case.

**Comment by mattstratton** [comment]
FWIW, I'm tracking the "Speakers" page in #51

**Comment by mattstratton** [comment]
I see what you're saying - it's like what I said up above in https://github.com/devopsdays/devopsdays-theme/issues/4#issuecomment-265882751

We have a template for "speaker", which shows all their bio stuff, including link(s) to their talks for this event. 

If a talk has multiple speakers, that's no big deal because that is set in the frontmatter of the talk itself, which lists all the speakers.

I think this is mostly solve-able at this point. Some of this was me conflating talks with people.

**Comment by mattstratton** [comment]
Also tracking this in #52 for individual speaker pages. I think we solved this.

**Comment by mattstratton** [comment]
https://dev.devopsdays.org/events/2016-minneapolis/program/nicole-forsgren for an example.

Bio is not showing up, etc.
