### ISSUE TITLE
Replace use of $.Now.Format

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#407]
Page's Now is deprecated. Instead of `$.Now.Format "2006-01-02"` we should probably be doing something like `(dateFormat "2006-01-02" now)` or something cleaner.

No reproduction steps

**Comment by jduv** [comment]
@mattstratton There's 16 instances of this across 12 templates. May I volunteer to knock this out?

**Comment by mattstratton** [comment]
It's all yours, my friend. Just wait until I merge https://github.com/devopsdays/devopsdays-theme/pull/409 because that might be some affected files.

**Comment by mattstratton** [comment]
#409 has been merged, so knock yourself out. Thanks!

**Comment by jduv** [comment]
Thanks. I have some ATL updates as well, look for a PR tonight.

**Comment by mattstratton** [comment]
Just remember there are two different repos for those two things :)

Because I am annoying like that.

**Comment by mattstratton** [comment]
See also #421
