### ISSUE TITLE
Add share buttons to homepage

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#422]
There are no share buttons on the homepage. This is a problem.

[ProdPad URL]( https://app.prodpad.com/ideas/27/canvas)

**Comment by mattstratton** [comment]
I really don't know where these buttons should go; any ideas?

**Comment by bridgetkromhout** [comment]
If we are talking about https://www.devopsdays.org/ I would think any sharing buttons would fit well at the bottom of the About section:

![screen shot 2017-05-11 at 1 55 55 pm](https://cloud.githubusercontent.com/assets/2104453/25966779/a04bec7a-3651-11e7-8d72-3a3cb0bade58.png)

**Comment by mattstratton** [comment]
I have a problem with any kind of CTA button being in a footer like that; I also wonder how much social sharing someone would do of the homepage itself anyway. Maybe they do? Hard to figure out.

The idea of the button is to make it a one click "I want to tell my twitter/facebook/whatever friends about this exact page!" which actually would be good for the homepage now that I think about it.

**Comment by bridgetkromhout** [comment]
Well, I think our choices are header or footer (problematic per your point about them being reused on other pages throughout the site), map/city logos (a weird choice, visually speaking), and left sidebar (probably the winner?) - if left sidebar, do you want them at the top or the bottom?

**Comment by bridgetkromhout** [comment]
This seems to be the same as https://github.com/devopsdays/devopsdays-theme/issues/272

**Comment by mattstratton** [comment]
yeah, we could do them in a row above the map, but I already hate how much of our content is pushed below the fold already.

**Comment by mattstratton** [comment]
Yep. I just closed that issue.

**Comment by bridgetkromhout** [comment]
> I already hate how much of our content is pushed below the fold already.

Hmmmmm. How do you feel about dropping the map to below all the city icons? This wouldn't have made sense before, but now we have colorful, varied, changing city icons...

**Comment by mattstratton** [comment]
You have no idea how happy that would make me. We have massive above the fold blocking javascript rendering right now (the map), which makes the user experience much slower.

I'm totally cool with mocking this up in a PR and seeing what it looks like.

**Comment by bridgetkromhout** [comment]
At this point (with the map dropped), if you don't want the CTA buttons for the homepage in the About, I'd put them at the top of the lefthand column.

**Comment by bridgetkromhout** [comment]
Reading through this issue, and here are the relevantbits:

@mattstratton:
> The idea of the button is to make it a one click "I want to tell my twitter/facebook/whatever friends about this exact page!" which actually would be good for the homepage now that I think about it.

And me:
>if you don't want the CTA buttons for the homepage in the About, I'd put them at the top of the lefthand column

I think that if we are going to add sharing buttons, a next step would be figuring out where they should be placed (given current site design).
