### ISSUE TITLE
speaker pics with .jpeg extenstion dropped from site

### ISSUE THREAD

**Issue by cacorriere** [devopsdays/devopsdays-theme#425]
### Expected behavior
.jpeg speaker profile pics work when testing the site locally and appeared in the netlify preview as expected. They were assumed fine for production.

### Actual behavior
.jpeg speaker profile pics are AWOL in prod after being merged and published.

### Reproduction Steps
Add .jpeg profile pics to test site. Check netlify. See them missing in prod.

**Comment by mattstratton** [comment]
I need to add `.jpeg` (and probably `.gif` to the gulp processing pipeline so we don't lose those images.

We will process `.jpeg` the same as others, but `.gif` we will just copy and fingerprint.
