### ISSUE TITLE
vertically align non-square sponsor logos

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#432]
### Expected behavior

All sponsor logos will be vertically aligned in a balanced-looking way.

### Actual behavior

Sponsor logos are top-aligned and it looks uneven.

### Reproduction Steps

The best example is https://www.devopsdays.org/events/2017-denver/welcome/ right now. See also:

![screen shot 2017-03-25 at 8 16 46 pm](https://cloud.githubusercontent.com/assets/2104453/24327512/c409a41e-1198-11e7-8f22-1663a068fd57.png)

**Comment by mattstratton** [comment]
Just making a note - the way to fix this is we should create a new class for `.sponsor_image` and set the formatting there.

**Comment by mattstratton** [comment]
I did a little hacking on this one, and it's beyond my CSS ability right now. It needs to be done, but it's not going to be trivial. Well, at least not trivial for me :)
