### ISSUE TITLE
center the city names under their logo squares

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#433]
### Expected behavior

City names looking well-balanced. 

### Actual behavior

They look a bit odd being left-aligned.

### Reproduction Steps

![screen shot 2017-03-25 at 8 42 55 pm](https://cloud.githubusercontent.com/assets/2104453/24327661/2d5ee138-119c-11e7-82a4-2d42ed5b9ab4.png)

Do we want to center them under their logo squares?

**Comment by mattstratton** [comment]
Presumeably we want to center the dates too, because it looks weird with just the names:

![devopsdays](https://cloud.githubusercontent.com/assets/1280666/24369788/be3bca14-12ea-11e7-94db-5d1b6296c73e.jpg)

**Comment by bridgetkromhout** [comment]
Definitely center everything, yeah.
