### ISSUE TITLE
Contextually style program elements - IDEA 17

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#435]
<p style=' color: rgb(36, 41, 46); font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-size: 14px; text-align: start; background-color: rgb(255, 255, 255);'>We should maybe add some special styling for Ignites or open space elements in the data file - ignites could be clickable to an anchor tag lower on the page to the ignite section too.</p><p style=' color: rgb(36, 41, 46); font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-size: 14px; text-align: start; background-color: rgb(255, 255, 255);'>Since the item blocks aren&#39;t really styled at all right now, we don&#39;t have a good way of doing this. I am thinking this could be an extension where we have some default &quot;types&quot; (right now I think it&#39;s just <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>talk</code> or <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>custom</code>, but we could add <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>open-space</code>, <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>ignites</code>, and maybe <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>sponsors</code> which would result in some different behavior/formatting).</p><p style=' color: rgb(36, 41, 46); font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-size: 14px; text-align: start; background-color: rgb(255, 255, 255);'>My theory is that for example, if the element is of type <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>ignites</code>, it would be a link to the anchor of the ignites section (which won&#39;t do much on a big screen, but will be awesome on a small one). And for <code style=' font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace; font-size: 11.9px; background-color: rgba(27, 31, 35, 0.0470588);'>open-spaces</code>, it could have a different color or something.</p>

[ProdPad URL](https://portal.prodpad.com/24442/ideas/357419)

**Comment by bridgetkromhout** [comment]
On the topic of Ignite styling, I'm noticing that on the current layout of the program page, they live in only in columns 1 and 3, which makes them wrap the text into a narrow column. They would probably look better stretched over columns 1-2 and then columns 3-4. To see this:

![screen shot 2017-04-23 at 5 38 22 pm](https://cloud.githubusercontent.com/assets/2104453/25318055/e6d722c2-284b-11e7-847c-a1dd1dff863e.png)

**Comment by kikicarbonell** [comment]
Do you consider the inclusion of workshop as new type and view style?

**Comment by mattstratton** [comment]
This is also related to #486. Individual workshops would have their own kind of page (just like a talk has a page for just that talk). The issue with workshops if they are at the same time as other things is that this program layout doesn't support multi-track, and we are unlikely to add that feature.

However, if you had a workshop day, where it was just another day of events, like an existing day, would be handled by the support of more than a two-day layout.

**Comment by mattstratton** [comment]
This shows a bit more of what I have in mind:

![](https://i.imgur.com/iqUjLaL.png)

**Comment by bridgetkromhout** [comment]
I like this. Is it possible to put the colored bubble around both the time _and_ the description, to better unify them?

**Comment by mattstratton** [comment]
Take a look at https://github.com/devopsdays/devopsdays-theme/pull/498 for how I'm thinking...

**Comment by bridgetkromhout** [comment]
I like this.
