### ISSUE TITLE
Add theme documentation for end-users - IDEA 66

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#443]
<p>This will be a document (stored in the root of the theme project) that contains all of the &quot;API&quot; documentation for the theme; what fields are available, how to use them, etc.</p>

Effort: 6/10
Impact: 10/10

**Comment by mattstratton** [comment]
Note - I am going to create a long-lived branch for this issue, so don't kill me.

**Comment by mattstratton** [comment]
Here's the file:

https://github.com/devopsdays/devopsdays-theme/blob/documentation-updates/REFERENCE.md

The branch is `documentation-updates`

**Comment by bridgetkromhout** [comment]
>  I am going to create a long-lived branch for this issue, so don't kill me.

🤣  You know me well.
