### ISSUE TITLE
events with overlapping dates have problems displaying

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#444]
### Expected behavior

All previous events no matter if they have overlapping dates (start or end) will appear on https://www.devopsdays.org/events/ and the front-page sidebar.

### Actual behavior

Seattle 2016 and Kiel 2016 had the same start and end dates. To sidestep this bug in the past, we listed a different start date (artificially). However, now the logic uses end dates, so currently only Seattle 2016 (and not Kiel 2016) shows up on https://www.devopsdays.org/events/.

This was known to be an issue in the new theme on the sidebar with start dates but was resolved somehow (see https://github.com/devopsdays/devopsdays-theme/issues/140). Not sure if problems still exist for the sidebar.

### Reproduction Steps

Set two past events to the same end date. View https://www.devopsdays.org/events/ and see that one is missing.

Same end date for Kiel and Seattle 2016:
![screen shot 2017-03-28 at 5 41 45 am](https://cloud.githubusercontent.com/assets/2104453/24401319/8e5403b8-1379-11e7-92e4-82a6cdc8bd0c.png)

Different end date for Kiel and Seattle 2016:

![screen shot 2017-03-28 at 5 41 57 am](https://cloud.githubusercontent.com/assets/2104453/24401328/96339616-1379-11e7-9b86-c517e7fda692.png)

**Comment by mattstratton** [comment]
FWIW, I gave seattle and hoofington the same start date in a local test, and they worked fine, so it doesn't affect the homepage grid or the sidebar.
