### ISSUE TITLE
Organizers should be sorted by name

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#460]
### Expected behavior
The list of organizers on the Contact page should be sorted by their name

### Actual behavior
They appear in the order that they are listed in the file.

### Reproduction Steps
Look at a /contact page.

**Comment by mattstratton** [comment]
My only concern about "fixing" this is that it might be too prescriptive; I can see cases where an event would want to have control over the order of the organizers as they are displayed. Thoughts?

**Comment by kmugrage** [comment]
Agreed with Matt's comment. Ours are alpha because that's what we wanted, but I wouldn't feel good about forcing that.

**Comment by bridgetkromhout** [comment]
We're alphabetical by first name on speakers, and that isn't yet configurable. It would be nice to have that be the default on organizers, but that gets into territory where then the organizers are behaving differently from the sponsors (which mostly should be in order-added).

It would be nice for it to have a defined and obvious default and then be configurable.

**Comment by mattstratton** [comment]
Basically, what I thought was that it would be something like "they are sorted by name, unless you toggle a `custom-sort` field, which just means 'sort them in the order they appear in the config file"

This would so NOT work for speakers, btw, because there literally isn't any way to control the order of the speakers since they are read in as a list of files; they aren't specfied.

This makes me think of a whole other better possible enhancement; although I think I already know how @bridgetkromhout will feel about it. We put so much data into the config file about the organizers now, and a lot of it needs to be escaped (well, the bio part). What would be more in line with the way we are starting to think about hugo (and the way hugo is starting to think about itself) is that each organizer has a page file, which has frontmatter for all the stuff, and the content of the file is the bio. So all you put in the YYYY-CITY file is the list of organizers, and then if there is an associated page for the organizer, it will pull data from that page (basically, the model in hugo now is "everything is a page"). 

Doing that does one really nice thing, which is makes us treat all references to humans the same way (there is a page for each human, and a summary page that shows the list of all the humans as they need to be grouped). NOTE: the scope of the "human" page is still at the event level; so it's not like the same file about that human is used cross-events, etc.

**Comment by mattstratton** [comment]
(the problem I have with the "change organizers to be individual pages instead of robust data elements" is that it's a pretty big change to existing events that started using the more robust organizer fields; but it would be fairly straightforward to make it backwards-compatible I think)

**Comment by mattstratton** [comment]
I also just realized that the idea of "treat all humans as pages" is more of an enhancement and beyond the scope of this fix, so I'm going to put that in as a possible future roadmap thing, and we can go back to just bikeshedding on the sorting of organizers using the current structure.

**Comment by mattstratton** [comment]
Looking at the code, having an override toggle is going to be slightly tricky (because the toggle only controls the initial `range` query, which means that we have massive duplication in the display code). 

Here's what I mean. It would look sorta like this (psuedo code)

```
{{ if eq $e.organizer_override "true" }}
   {{ range $e.team_members }}
      <whole bunch of code that lists all the stuff>
   {{ end }}
{{ else }}
  {{ range $e.team_members sort by name }}
      <same code that was listed above>
  {{ end }}
{{ end }} 
```

That is super not DRY, and it means that every time we change anything with how an organizer is displayed, we do it in two places in the code. Which means we will miss something.

The major issue I see with sorting by `name` is that we have now enabled the ability to add roles to the organizer's display (merged but not released) so I could see the desire to manually control the sort.

**Comment by bridgetkromhout** [comment]
Given that events currently can control the sort precisely as desired by choosing the order-in-file, I'm not sure this is a problem that warrants "solving". Perhaps we just document and move on?

**Comment by mattstratton** [comment]
I suggest we close this `wontfix`. I don't remember who wanted this; if they decide they want it, they can open their own issue :)
