### ISSUE TITLE
Open CFP widget in footer shows CFP's that aren't open yet

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#462]
Similar to #448 

### Reproduction Steps
View the footer and see that there are events listed where the CFP isn't open, but the value is set.

**Comment by bridgetkromhout** [comment]
There's duplicate code here - probably the best approach would be if we can refactor so the events page and sidebar are using common code. Otherwise, bringing in the fix from the events page is a good option.

**Comment by mattstratton** [comment]
I'm going to take a quick look and see if it's easy to do with a partial.

**Comment by mattstratton** [comment]
This doesn't quite work well with a shortcode because it's just a matter of changing the query; it was super simple to fix though.
