### ISSUE TITLE
add defined place on event contact page for organizer's role

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#463]
### Expected behavior

It should be easy for attendees to tell, by looking at an event's contact page, who's in charge of what. This will help them know if there's a specific person to talk to at the event, and clarify what people are doing on the organizing committee. Ideally this would be an opt-in field in the yaml, and displayed somewhere it won't be confusing (ie, not right by their employer).

### Actual behavior

While we could write it into bios, we don't have a specific field for "Sponsor Coordinator" or "Venue Wrangler" or "Registration Head" or whatever.

### Reproduction Steps

Look at any new-style contact page.

**Comment by mattstratton** [comment]
I was totally thinking about this the other day! Great minds. I didn't know if this was a thing that people tended to want to display, but if it's opt-in, then yayyayyay.

**Comment by mattstratton** [comment]
Here's a preview of what the layout would look like - if the role is set, it displays the role, otherwise it just says "organizer"

![contact](https://cloud.githubusercontent.com/assets/1280666/24561463/74e0ef6e-160c-11e7-85cb-63aee221f8ee.jpg)

**Comment by bridgetkromhout** [comment]
I like this. Thanks!
