### ISSUE TITLE
Events feed needs more robust information

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#474]
I've started to use the feed at https://www.devopsdays.org/events/index.xml to populate a Twitter feed - it's a good start, but needs some more info.

As an example, take a look at what Atlanta looks like:

```
<item>
<title>devopsdays Atlanta 2017</title>
<link>https://www.devopsdays.org/events/2017-atlanta</link>
<guid>https://www.devopsdays.org/events/2017-atlanta</guid>
<pubDate>Thu, 6 Apr 2017 21:40:05 +0000</pubDate>
<description>
devopsdays Atlanta 2017 will be taking place Tue, 18 Apr 2017 through Wed, 19 Apr 2017.
</description>
</item>
```

When I pull this up in the system to generate the posts from the feed, it looks a little like this (this shows Chicago because, um, that's what I pulled up):

![meetedgar](https://cloud.githubusercontent.com/assets/1280666/24800180/b21d05ea-1b64-11e7-8ba2-36068fb16815.jpg)

The key thing is that of course the system I'm using only uses Title for the tweet, which makes some sense because Description is too long. 

The feed only contains items which are the upcoming events and an item pointing to the root page for that event, and it does NOT use the title set on the page; the code is this:

```
<title>devopsdays {{ .city }} {{ .year }}</title>
```

I'm suggesting we make a bit more robust title - something like "DevOpsDays Chicago 2017 is coming! Sept 12&13" (if a date is set) or then "DevOpsDays Chicago 2017 is coming! Date TBD!" if it's not set (alternatively, we could only include events with a startdate in the feed?)

Thoughts?

**Comment by bridgetkromhout** [comment]
If we're going to be opinionated on behalf of cities let's use `devopsdays` not `DevOpsDays`, but other than that stray thought, this sounds good to me. I'd just offer the ones with dates set, personally. Without dates we can't promise much!

**Comment by mattstratton** [comment]
Good point. Should make sure the query checks for events with `.startdate`.

**Comment by mattstratton** [comment]
I just looked a bit at the feed...it seems to only include events with startdates anyway?

Basically, it just means we should add some extra flavor around the title of the feed element. and yes, it can be in lowercase :)
