### ISSUE TITLE
embedded google forms aren't responsive

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#475]
### Expected behavior

Embedded google forms should look normal on all devices (if at all possible).

### Actual behavior

Off-centered on some phones as described in https://twitter.com/add_action_dan/status/850510923580289024:

![image](https://cloud.githubusercontent.com/assets/2104453/24824174/83484230-1bcc-11e7-9a56-bc83f101e29d.png)

And when I tested in a narrow window, google forms don't appear to be responsive.

### Reproduction Steps

Try in a narrow viewport.

**Comment by mattstratton** [comment]
If only there was a shortcode for embedding google forms where we could then control the div's around them and make them responsive ;)

**Comment by bridgetkromhout** [comment]
> If only there was a shortcode for embedding google forms where we could then control the div's around them and make them responsive ;)

Pull requests accepted. =)

**Comment by mattstratton** [comment]
Duplicate of #230
