### ISSUE TITLE
fix datetime issues with CFP

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#476]
### Expected behavior

CFP would remain open through end of day local time (in the absence of a hour/minute setting which we don't yet have). Not actually expected - just incorrectly assumed. 

### Actual behavior

After midnight UTC, CFP appears closed on deployed site even though end of day isn't yet reached in the local TZ. Note that Minneapolis is missing on the deployed site but still appears locally. Conclusion: datetime is sadness.

![screen shot 2017-04-09 at 7 26 24 pm](https://cloud.githubusercontent.com/assets/2104453/24842301/1b953dec-1d5b-11e7-907e-721dcf70f683.png)

![screen shot 2017-04-09 at 7 26 33 pm](https://cloud.githubusercontent.com/assets/2104453/24842299/163785f8-1d5b-11e7-8119-ef71231db90e.png)

### Reproduction Steps

Set a CFP date to closing on a given day, and check after UTC-midnight.

**Comment by bridgetkromhout** [comment]
This is related to many other issues that we're probably going to have to solve with a real datetime. Le sigh.

**Comment by mattstratton** [comment]
Truth be told, as annoying as it is, having the time will actually help us a bit with some additional features (regarding knowing exactly when something ends, like CFP's, etc) 

Plus I have a sneaking suspicion this will solve our occasional event ordering problem.

**Comment by bridgetkromhout** [comment]
Anything we fix, let's document in https://github.com/devopsdays/devopsdays-theme/blob/master/REFERENCE.md#date-related-fields too.

**Comment by bridgetkromhout** [comment]
This is solved by https://github.com/devopsdays/devopsdays-web/pull/5213 - thanks, @tgross!
