### ISSUE TITLE
Inconsistency in booleans in event data files

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#478]
Sometimes we look for "true" (cfp_open), and sometimes "yes" (sponsors_accepted)

I suggest we change the default mechanism/examples to be "yes/no", but accept "true/false" for backwards compatibility.

No reproduction steps.

**Comment by mattstratton** [comment]
This is a pain in the neck for questionable value.

**Comment by bridgetkromhout** [comment]
I am not sure whether this could ever provide enough benefit to be worthwhile, and I propose closing it as "wontfix".

**Comment by mattstratton** [comment]
Yeah, it doesn't seem to have been in a problem in the last 12+ months, so I suppose we are good with that.
