### ISSUE TITLE
adjust dates as shown on frontpage

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#481]
### Expected behavior

We've done a little bikeshedding on this before, but I figure that submitting working code is the best way to demonstrate what I think it should look like. It's bugging me right now because Tokyo is in the top row (it's this month) and has this problem. But Paris and likely other one-day events are coming soon too.

I'd like to see the dates on the frontpage center section handled the same as they're handled in the left sidebar. That is to say, we don't need start and end date if they are the same, and we only need to list the month on both dates if it varies.

### Actual behavior

Pointless duplicate of the month when it doesn't vary and of the start/end dates when they are the same:

![screen shot 2017-04-15 at 10 03 43 am](https://cloud.githubusercontent.com/assets/2104453/25064651/3a62768c-21c4-11e7-9f4d-f3aaeefbb1e7.png)

### Reproduction Steps

You can see this in action just by looking at the front page. Here are screencaps of the fix when applied locally:

![screen shot 2017-04-15 at 10 03 11 am](https://cloud.githubusercontent.com/assets/2104453/25064663/847b5a18-21c4-11e7-9295-f77bddd7131a.png)

And with Minneapolis mocked up to have dates spanning a month boundary:

![screen shot 2017-04-15 at 10 08 24 am](https://cloud.githubusercontent.com/assets/2104453/25064666/918e2b9a-21c4-11e7-9b5b-7347a7dad015.png)

**Comment by mattstratton** [comment]
Huh. I thought I'd fixed this in the previous fix. Whoops.
