### ISSUE TITLE
Front page logo align on mobile

### ISSUE THREAD

**Issue by kramos** [devopsdays/devopsdays-theme#483]
### Expected behavior
Front page logos look nice on mobile
### Actual behavior
The images are left aligned and due to the different sizes look a bit untidy.
![dod_align](https://cloud.githubusercontent.com/assets/2998508/25140508/82cd3f06-2458-11e7-98ef-12c723c53a53.png)

### Reproduction Steps
Looked on an Iphone 7 in Chrome
Replicated in Chrome on Windows > Developer Tools > Iphone 6 view (screenshot taken from this).

### Operating System and Version
iOS 10.3.1
### Web Browser and Version
Chrome latest

### Suggested fix:
I was able to fix this by adding: 
`text-align: center;`
to
`homepage-grid-col`
But I did it in `devopsdays-theme/static/css/site.css ` which I think is the wrong place (sorry not very css savvy).

**Comment by bridgetkromhout** [comment]
Thanks, @kramos! We'll see what we can figure out.

**Comment by mattstratton** [comment]
Knowing the CSS selector to change will be helpful - it needs to be changed in the sass file but I know how to fix it based on this :)

**Comment by kramos** [comment]
Hi @mattstratton, is it `.homepage-grid-col` ?

![image](https://cloud.githubusercontent.com/assets/2998508/25202087/fc61e076-254b-11e7-8a29-ca21f88f9f91.png)

**Comment by mattstratton** [comment]
Oh I wasn't asking for it - you told me what it was! I was saying this feedback was super helpful because you already figured out the base CSS and now I can get it in the right file :)

**Comment by mattstratton** [comment]
I will need to test this in multiple browsers but I'll pull it in as a fix sometime in the next few days and try it out on IE, etc.
