### ISSUE TITLE
Speaker images of different sizes act differently

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#485]
### Expected behavior
All images on the speaker page should look the same regardless of the actual file dimensions

### Actual behavior
They resize in a weird way.
![](https://i.imgur.com/lzndN8B.png)

### Reproduction Steps
Use images of different dimensions for speakers

**Comment by bridgetkromhout** [comment]
Related, I think, to this issue - when speaker images _aren't_ square, they don't stay inside the confines of an imagined square.

To see: https://deploy-preview-2322--devopsdays-web.netlify.com/events/2017-seattle/speakers/

![screen shot 2017-04-23 at 5 34 00 pm](https://cloud.githubusercontent.com/assets/2104453/25318007/3b802ab8-284b-11e7-908b-6d7f7a3317c0.png)

**Comment by mattstratton** [comment]
Well, tbh, we can't really constrain them to a square automatically without auto-cropping which might make them look weird. 

Maybe the answer is speaker/organizer images need to be square in general? Gives us more predictability in the layout.

**Comment by bridgetkromhout** [comment]
I was imagining auto-adding padding to fill them out to square size.

**Comment by mattstratton** [comment]
This is the kind of thing that sounds like it would be super simple, but the predictability makes it rough. 

We either try to do it in the front-end code itself, which means we have to look at every image at build time and figure out if we add some padding (no real idea how you do that - "add padding" that is), or we can do it in the pipeline, which will make the image processing process even longer.

It's safer and more predictable to require people to crop their own images IMHO.

**Comment by bridgetkromhout** [comment]
Minneapolis has a good example of this - Duretti's picture is larger and on mobile looks larger.

![msp](https://cloud.githubusercontent.com/assets/2104453/25966325/4e43d5ce-3650-11e7-956d-85d5319943f3.PNG)

**Comment by mattstratton** [comment]
I was mentally bikeshedding about this the other day, and the answer is to specify where the speaker images go.

For example, we do this with the organizer images, which means that our image processing can make them the same size, to wit:

```
gulp.task('responsive-organizer-images', function() {
  return gulp.src('public/**/organizers/*.jpg')
    .pipe(responsive({
      '**/*.jpg': [{
        width: 300,
        height: 300,
      }, {
        width: 600,
        height: 600,
        rename: {
          suffix: '@2x'
        }
      }, {
        width: 900,
        height: 900,
        rename: {
          suffix: '@3x'
        }
      }],
    }, {
      // global configuration
      quality: 80,
      errorOnEnlargement: false,
      withoutEnlargement: false,
      progressive: true,
      silent: true,
      withMetadata: false,
      ignoreAspectRatio: true,
    }))
    .pipe(gulp.dest('dist'));
});
```

**Comment by mattstratton** [comment]
So what I'm thinking is that you put your speaker images in `static/events/YYYY-CITY/speakers/` like you do for organizers.

Sadly, we let people specify the filename (I don't recall why) so doing something like "we just look for a jpg with the same name as the speaker" won't work, unless we do some defensive coding like "if I cannot find one then I'll pull it from the frontmatter".

Actually, that might not be a bad idea. We default to look for it in the speakers directory, if it's not found there, we see if it's set in the frontmatter, and if THAT fails, we show the default image.

**Comment by bridgetkromhout** [comment]
> Sadly, we let people specify the filename (I don't recall why)

We could just... not. I mean, I don't think that's remotely useful or needed.

**Comment by mattstratton** [comment]
Well we already have it, so we have to code for it. But we can totally remove that "ability" (fix it in the script and the documents), but the code has to still pull those for safety.

Although we could do a bit of a eyeball check to see how much manual fix it would be; if we could fix the existing events (which are only ones who added speakers after `devopsdays-theme`), we could make the code look directly for the speaker by filename in the `speakers` directory of static.

**Comment by bridgetkromhout** [comment]
>  if we could fix the existing events (which are only ones who added speakers after devopsdays-theme), we could make the code look directly for the speaker by filename in the speakers directory of static.

I like this plan.

**Comment by mattstratton** [comment]
This is also part of https://github.com/devopsdays/devopsdays-theme/issues/507

**Comment by mattstratton** [comment]
It looks like you have to put the speaker images in the `static/events/YYYY-CITY/speakers` directory already anyway :)

**Comment by mattstratton** [comment]
So here's my proposal:

1. Require speaker images to be in the `speakers` directory of the event's static directory (this is already true, but I want to confirm the docs reflect that
2. Require speaker images to be square in the docs
3. Require speaker images to be 300px square, 600px square, or 900px square.
4. In post-processing, we will retinafy them to those three sizes

**Comment by mattstratton** [comment]
Okay, so I did a little digging:

1. This is true in the code; you cannot override it. In the PR I am going to submit, I clarify this in the docs.
2. This is not currently in the docs, but I updated the docs in the PR.
3. See number 2.
4. I updated gulp to do this. In some cases, this is going to make a really shitty looking image (for example, Amsterdam has a TINY image for Arnab Sinha, and it gets blown up to 300px square and looks pixely, but hey, whatcha gonna do?) For non-square images, it actually seems to work sorta okay; this is a case of YMMV in how the gulp task decides to crop it.

**Comment by mattstratton** [comment]
OK, so I tested this build in dev, and you can see how it works. Compare these two pages:

https://www.devopsdays.org/events/2017-amsterdam/speakers

vs

https://dev.devopsdays.org/events/2017-amsterdam/speakers

@yvovandoorn

**Comment by yvovandoorn** [comment]
Hey @mattstratton, I am a pro on this change. It creates consistency and a more predictable layout. Sure it messes with some of the photos for some of speakers but to me consistency/predictability over some of the lob sided images.

I'm 👍 on this.

**Comment by mattstratton** [comment]
okay cool. we shall make it so :)
