### ISSUE TITLE
Test and validate with Hugo 0.20

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#494]
We are a little behind on hugo versions (we are compatible with 0.19 as of now) and we need to certify on hugo 0.20, as it would be nice to take advantage of some new features.

Anecdotally, we seem to be fine, but need to validate this.

**Comment by mattstratton** [comment]
At this point, when I upgraded to hugo v0.20.7, the site builds fine with no errors. I am checking with Netlify to see if hugo is available on their build servers in order to do the update.

To be honest, the TravisCI checks on devopsdays-web always pull latest hugo, so we knew it built fine anyway :)

**Comment by mattstratton** [comment]
Annoyingly, .19 is the latest version on netlify.

So unless I want to shove the binary into the devopsdays-web repo (I don't) we are stuck with it for now.

**Comment by mattstratton** [comment]
A defect was discovered with links to events when running Hugo 0.20; a good test case is 2017 Chicago or 2017 Oslo.

**Comment by bridgetkromhout** [comment]
I think you did update to .20.x with a custom binary - can you bring this issue up to date? Thanks!

**Comment by mattstratton** [comment]
Actually it got even better - they fixed the issue and I've updated the `netlify.toml` in this repo to use 0.20.7, so I can close this issue.

**Comment by mattstratton** [comment]
Oh, and I do need to make a change on `devopsdays-web`, but since I want to touch the gulp build over there shortly, I'm going to put that into one change.
