### ISSUE TITLE
Add feature toggles

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#50]
Certain features should probably be "opt in"; it's slightly easier to do this as a configuration toggle than shortcodes (because that requires less effort on the part of the user).

For example, let's say the default is to show all the speakers on the welcome page. But you don't like that. We should have a feature flag called "displaySpeakers" which you can set to "false".

**Comment by mattstratton** [comment]
What actual features are we toggling?

I think we decided to remove the "all speakers" option on the homepage anyway.

**Comment by bridgetkromhout** [comment]
I don't see a huge amount of demand for this and am not convinced it's worth our time.

**Comment by mattstratton** [comment]
yeah, let's wait until there's a feature to toggle.
