### ISSUE TITLE
Improve retina creation process

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#507]
Right now we retinafy all the images. Doing so for organizer images and image logos doesn't take much time (a few seconds). Sponsor images takes about 2 minutes.

It takes upwards of 3 minutes to just do this for "all remaining images", and there is no actual benefit.

Suggestion to improve this:

- [ ] Only retina speaker images in the "speakers" directory of an event's static files. We will specify the dimensions for speaker images similar to how we do so for organizers. We can probably allow for override in this manner; if none is set, it tries to find an image in that directory that matches the name, otherwise they can specify it as relative to the location.
~- [ ] Remove the "other images" step in gulp~
- [ ]  Create a "retina image shortcode" which takes the relative path of a base image and will return retina-friendly version. I'm pretty sure that hugo now can read the dimensions of an image, so we can take whatever the size of the image is, and apply a "max-width" of half of it, and then create all the srcset attributes for 1x and 2x versions. This shortcode will require the users to place properly named files where they need to be, but it could be super useful.

**Comment by mattstratton** [comment]
FWIW, we cannot do the second item listed above, because the retina thing is stupid.

**Comment by bridgetkromhout** [comment]
I don't have strong opinions about this, except to say...

> This shortcode will require the users to place properly named files where they need to be,

I'm fine with us being like "you must".

**Comment by mattstratton** [comment]
The thing that I have since realized is that we have to retinafy all the images. There's no way to leave some images out of it, because the gulp task that generates the `srcset` stuff is stupid and does it for all images, not just ones that have a corresponding retina image (even though that's how it's documented to work). This whole thing is going to take some thinking.

**Comment by bridgetkromhout** [comment]
Question: should we resolve this as `WONTFIX` due to the fact we don't create retina images now?

**Comment by mattstratton** [comment]
Agreed.
