### ISSUE TITLE
Markdown in program files should be displayed

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#514]
If an event enters some markdown/content in their `program.md` it should show up somewhere on the program page (an event might have things to put on the program page besides the schedule itself).

TBD is if it goes above or below the schedule; i am leaning towards below.

**Comment by mattstratton** [comment]
Although based upon a slack comment just now, it would seem @bridgetkromhout prefers the content to be above the schedule.

I would think what we do, if we do that, is make it above the schedule on large viewports, and on small viewports stack it below, as someone could add a whole crapload of stuff and when on mobile, you really just want to see the schedule first.

**Comment by bridgetkromhout** [comment]
Depends on what people are adding. I've seen things like "there are two days of programming, and look at this explanation of what Open Space is".

**Comment by mattstratton** [comment]
Yeah, we can't really offer that level of customization without putting in a toggle.

**Comment by kmugrage** [comment]
I'd prefer above, as it may give information that would make understanding the schedule easier.
