### ISSUE TITLE
Speakerdeck width overlapping with speaker profile text

### ISSUE THREAD

**Issue by Roderick-Jonsson** [devopsdays/devopsdays-theme#531]
The speakerdeck widths are too large and take away the space of the speaker profile.
https://www.devopsdays.org/events/2017-zurich/program/alex-lichtenberger/

Reproduction Steps:
![devopsdays - issues - speakerdeck width to large](https://cloud.githubusercontent.com/assets/10051979/26036199/7ffc1dde-38d9-11e7-9352-b80955055536.png)

**Comment by mattstratton** [comment]
Hmm. This shouldn't happen...browser and OS please?
