### ISSUE TITLE
The "about" sidebar should not be special-cased

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#532]
### Expected behavior

I expected https://www.devopsdays.org/about/ to use the same left sidebar as the rest of the site.

### Actual behavior

There appears to be a special-cased sidebar used only for the "about" page:

![screen shot 2017-05-15 at 5 11 07 pm](https://cloud.githubusercontent.com/assets/2104453/26081641/852747d0-3991-11e7-9d29-109d2af8d050.png)

versus

![screen shot 2017-05-15 at 5 10 50 pm](https://cloud.githubusercontent.com/assets/2104453/26081645/8a3233b6-3991-11e7-91a4-19e2ed512427.png)

### Reproduction Steps

Look at the sidebar for this page versus any other.

**Comment by bridgetkromhout** [comment]
This appears to happen because of https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/partials/about.html and https://github.com/devopsdays/devopsdays-web/blame/master/content/page/about.md#L7. It goes away when I change the type of that page. Unsure why I set it up this way in the first place.

**Comment by bridgetkromhout** [comment]
Ah  - that partial produces the list at the end of the page. It doesn't explain why the left sidebar is slightly wrong.

**Comment by bridgetkromhout** [comment]
The list looks kinda terrible anyhow and having that "type" in place overrides the preferred sidebar. In the interests of simplicity, I'm cleaning this up:

![screen shot 2017-05-15 at 8 30 09 pm](https://cloud.githubusercontent.com/assets/2104453/26086008/a9ac6222-39ad-11e7-8674-5c2535e34637.png)

Cleanup of data: https://github.com/devopsdays/devopsdays-web/pull/2438
Cleanup of theme: https://github.com/devopsdays/devopsdays-theme/pull/533

**Comment by bridgetkromhout** [comment]
The terrible-looking list, for when we've blissfully forgotten:

![screen shot 2017-05-15 at 8 37 39 pm](https://cloud.githubusercontent.com/assets/2104453/26086114/65827f5e-39ae-11e7-897e-a5bf22a42214.png)

**Comment by mattstratton** [comment]
Fixed in #533
