### ISSUE TITLE
Improve title tags to remove duplication in Google

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#539]
According to Google:

```
Duplicate title tags
Your title provides users and search engines with useful information about your site. Text contained in title tags can appear in search results pages, and relevant, descriptive text is more likely to be clicked on. We recommend reviewing the list and updating the title tags wherever possible.
```
We have 355 pages in the index with duplicate titles. This is because the default titles for pages are things like "propose", etc.

Suggestion is that we prepend/appends CITY YEAR - title to the title of the elements. 

For example, instead of the title of a propose page being "propose", it would be "devopsdays Ponyville 2017 - propose"

The tricky bits here are forcing this in; if someone sets a "good" title, you could end up with something like "devopsdays Ponyville 2017 - devopsdays Ponyville Proposals!"

What we *could* do is a check to see if the title is set to one of the standards (there aren't that many) and only prepend it if needed.

I also see this duplication in talks, since the talks are named after the person, so we have several title duplications of something like "Adam Jacob", but that only happens when they don't actually make a good title. 

Another way to do this is to see if the title matches the filename in a way...

**Comment by bridgetkromhout** [comment]
We've solved this going forward by setting city-year in the default frontmatter, right? If it's solved going forward, we could retcon that frontmatter into old events.

**Comment by mattstratton** [comment]
Yep, you've solved it there. What I was thinking we could do is just put in a little bit of logic that overrides it if the title is eq to `contact` or any of the "old" single ones. That way we don't have to change the content.

> What we could do is a check to see if the title is set to one of the standards (there aren't that many) and only prepend it if needed.

That's what I'm thinking.

**Comment by mattstratton** [comment]
This is actually what is starting to cause the old events to come up higher in ranking - or at least the confusion. The old `welcome.md` page has a title of "welcome"...Google thinks that is a stupid title, so they change it in the SERP to be "devopsdays CITY"...but if the title had already been "devopsdays CITY YEAR", even if it ranked higher, it would show the year in the SERP.

So I think what we need to do is a quick bit of bash-fu to search/replace all the title frontmatter in the `welcome.md` to be "devopsdays CITY YEAR".
