### ISSUE TITLE
Broken links in the CFP RSS feed

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#540]
@mattstratton to investigate - see https://github.com/devopsdays/devopsdays-web/issues/2460

### Expected behavior

Working RSS feed

### Actual behavior

See reported issue

### Reproduction Steps

View erroneous feed

**Comment by xaprb** [comment]
The feed at https://www.devopsdays.org/speaking/index.xml has entries that lead to 404 error pages. Example: 

```
<item>
          <title>devopsdays Bangalore 2017</title>
          <link>events/%!(EXTRA string=2017-bangalore)</link>
          <guid>events/%!(EXTRA string=2017-bangalore)</guid>
          <pubDate>Sat, 20 May 2017 17:55:39 &#43;0000</pubDate>
          
            <description>Devopsdays is coming to Bangalore!</description>
          

        </item>
```

**Comment by xaprb** [comment]
It looks to me like URLs of the following format are "always" valid:

    https://www.devopsdays.org/events/2017-bangalore/propose/

And the (possibly external) CfP link seems to be shown there in all cases. I may be stating the obvious, sorry if so; haven't done a lot of research on this. In my feed reader, recent entries have the broken format shown here:

    https://www.devopsdays.org/speaking/events/%!(EXTRA%20string=2017-bangalore)

**Comment by mattstratton** [comment]
This is definitely just a bad `printf` formatting in the template (based on the described errors) so it should be an easy fix when I get a chance. 

To set proper expectations, I don't expect to look at this until after I get back from ChefConf, but it should be quick after that.
