### ISSUE TITLE
[Enhancement] Add Flickr social sharing button

### ISSUE THREAD

**Issue by Roderick-Jonsson** [devopsdays/devopsdays-theme#541]
We uploaded a photo gallery of our event on flickr and would like to add this to our page on DevOpsdays.
https://www.flickr.com/photos/150616602@N02/

**Comment by mattstratton** [comment]
What do you have in mind? There's nothing preventing you from adding it to your welcome.md (that allows HTML).

**Comment by Roderick-Jonsson** [comment]
@mattstratton When I look at our main page https://www.devopsdays.org/events/2017-zurich/welcome/ to the right there are this sharing buttons which can be added by filling out the corresponding tags https://github.com/devopsdays/devopsdays-theme/blob/master/REFERENCE.md but we seem not to have a flickr button. I hope this explained it better to you.

**Comment by mattstratton** [comment]
Thise sharing buttons are to share your URL onto twitter, etc. i.e., take the URL of your homepage and the person who clicks the button shares it to their twitter or Facebook stream. 

If you want a button to take people to your Flickr album, that's not really where it would go, as those buttons are the common "share this page on X social network).

**Comment by Roderick-Jonsson** [comment]
@mattstratton Ok got it
