### ISSUE TITLE
add twitter handles to talk pages

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#551]
### Expected behavior

Easy and fast to find the twitter handle for livetweeting.

### Actual behavior

Even though in theory I know where it is, I find myself doing a double-take constantly when I don't see twitter handles. Then I remember oh, right - click through to the speaker page. While we won't be putting _everything_ from the speaker page onto each talk page, the utility of a twitter handle for live tweeting is pretty crucial.

And it doesn't add too much clutter:

![screen shot 2017-06-06 at 3 57 04 pm](https://user-images.githubusercontent.com/2104453/26851956-2c8efdc8-4ad2-11e7-879d-ddbab05b23ca.png)

### Reproduction Steps

Look at speaker pages and talk pages.

**Comment by mattstratton** [comment]
Why not all the rest of the icons, for consistency?

**Comment by bridgetkromhout** [comment]
None of the other icons are necessary for the face-paced limited use case (livetweeting) that would make it useful to surface more info right on the talk page instead of requiring slower in-depth reading of a speaker's full profile.
