### ISSUE TITLE
Refactor how "talks" are displayed on a speaker's page

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#554]
In order to support the idea of workshops, etc, we need to change how the items associated with a speaker are displayed. Currently, it looks like this:

![](https://i.imgur.com/GwbFVlQ.png)

The use of the word "talks" is a little odd, because it also includes ignites and workshops. Rather than breaking it down into "workshops by...", "talks by...", etc, it should just list all the presentations (for lack of a better word) that this person is presenting/responsible for.

We can solve this two ways:

1) Keep the same layout idea (with a title) and change "talks" to "presentations", which might be misleading.
2) Remove the idea of a title element altogether, and figure out a way to display the list in a method that doesn't require descriptive text.

**Comment by mattstratton** [comment]
@yvovandoorn @bridgetkromhout your thoughts?

**Comment by bridgetkromhout** [comment]
What if we changed the title to Cityname Year? That would make it easier to also add past/future stuff for other cities on this page (something I've been toying with).

**Comment by mattstratton** [comment]
Ah, thinking along the lines of what I did in castanet where it shows episodes for that guest, including "aka" ones. That might be tricky to figure out how to find that speaker across other events though. 

I'm sorta trying to just think of a different layout of displaying that altogether, although I do like the idea of cityname year - even though it might seem redundant, someone might find that page via google, etc, and not have context for what that page is, so that really helps!
