### ISSUE TITLE
[Enhancement] Some people think 'Open Space' in the Program means not taken

### ISSUE THREAD

**Issue by kramos** [devopsdays/devopsdays-theme#583]
### Expected behavior
We expect visitors to see "Open Space" and think the same as us - "Good this is DevOpsDays, there are open spaces in the afternoon".  

### Actual behavior
People who haven't heard of open spaces sometimes think "Good there are still open (as in not filled) slots in the agenda for me to do a 30 minute talk - I'll email the organisers".

### Suggested behavior
We help people understand what we mean by making the Open Space slots clickable so that they link to the page about what an open space is.

I implemented the code change before here:
https://github.com/devopsdays/devopsdays-web/pull/2832
but raised it in the wrong repo (sorry for wasting your time before).

If you like this, I'll submit as a PR here.

**Comment by mattstratton** [comment]
I would definitely not use the `printf` approach...and we want to make sure to use `absURL` because reasons.

I would say change this line:
```
<a href="{{ (printf "../../../open-space-format/") }}">
```

to
```
<a href="{{ "open-space-format/" | absURL }}">
```

If you want to throw that into a PR on this repo, I'll check it out.
