### ISSUE TITLE
Extra dash on program page if speaker is blank

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-theme#586]
### Expected behavior

Sessions with a named speaker show up as "Speaker - Title"
Sessions without a named speaker show up as "Title"

### Actual behavior

Sessions without a speaker show up as "- Title"

### Reproduction Steps

Create a talk with no speaker like https://github.com/devopsdays/devopsdays-web/pull/2985

![image](https://user-images.githubusercontent.com/3209933/29465278-9bbb49a0-83ed-11e7-9889-5bc75c6bc58c.png)

**Comment by bridgetkromhout** [comment]
Hi, @kmugrage  -

I'd recommend that @broamski make that a "custom", not a "talk", program item. There's logic built in that assumes talks have speakers:

<img width="831" alt="screen shot 2017-08-18 at 11 12 41 am" src="https://user-images.githubusercontent.com/2104453/29467455-4165c372-8406-11e7-9dd8-046b7f0342bf.png">
