### ISSUE TITLE
Use a different method for specifying an event homepage

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#59]
Related to #47 

Perhaps on the "welcome" pages, we add a new frontmatter tag, like `homepage = "true"`, to specify that this is the homepage for an event and should get the extra love.

The other option is to create a new template called `layouts/welcome/single.html` and set the type of the welcome page to `welcome` in the frontmatter; this actually follows the convention of the other "special" pages (talk, program, speaker, etc) more closely.

This also will better preserve backwards-compatibility.

**Comment by mattstratton** [comment]
FWIW, I prefer the latter option (creating a new layout for "welcome" pages, and making the index page be of that type). Given that events are created using the script/sample event, we should be able to create a structure like this:
```
YYYY-CITY (directory)
- index.md (aliases to /events/YYYY-CITY/welcome/ and is of kind = welcome)
- location.md
- program (directory)
-- some_talk.md (is of kind = talk)
- program.md (is of kind = program)
```

Thoughts, @bridgetkromhout ?

**Comment by bridgetkromhout** [comment]
This is fine by me.
