### ISSUE TITLE
change organizers page to use https for twitter and github

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#595]
### Expected behavior

Use https for twitter and github to prevent unneeded redirects.

### Actual behavior

Currently using http on the organizer page. As @adrianmoisey put it in the [PR](https://github.com/devopsdays/devopsdays-theme/pull/594), "both GitHub and Twitter are served on https. Linking to the http version causes a redirect."

### Reproduction Steps

See the http links on https://www.devopsdays.org/events/2017-cape-town/contact/.

I checked and we're correctly using https on the [CTA](https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/partials/events/cta.html#L77), [footer](https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/partials/footer.html#L9), [shortcodes](https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/shortcodes/event_twitter.html), [speaker page](https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/speaker/single.html#L21), [talk page](https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/talk/single.html#L131). This seems to be the only place twitter was http.

**Comment by mattstratton** [comment]
This was fixed in #594
