### ISSUE TITLE
Default speaker image is too big

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#597]
The default speaker image is still a larger size than what we resize speaker images to, so it looks goofy.

### Reproduction Steps

![devopsdays_madison_2017_-_speakers](https://user-images.githubusercontent.com/1280666/30653554-024d2edc-9df1-11e7-9968-eea5bb715fc2.png)

**Comment by peterjshan** [comment]
@mattstratton I can take this one, few questions.

1. What default speaker image?
2. The images are resized dynamically, would you be willing to discuss automating the resizing of image files to keep them at consistent sizes?

re: ![devopsdays_galway_2017_-_speakers](https://user-images.githubusercontent.com/1648741/32371986-635cb914-c069-11e7-997c-2b28d4962d3b.png)

**Comment by mattstratton** [comment]
For number 2, they are resized consistently in a gulp task when merged to master.

**Comment by mattstratton** [comment]
This is where the default speaker image lives:

https://github.com/devopsdays/devopsdays-theme/blob/master/static/img/speaker-default.jpg

**Comment by mattstratton** [comment]
This is where we reside in gulp, so ideally we have two versions of default speaker. 

Thinking more, it might make more sense to add the default speaker image path to the capture group for that gulp task so it’s resized the same way as all the other speaker images.

**Comment by peterjshan** [comment]
I understand my confusion now. What I am running locally is not what's running on dev.*, and is also not what's running in production because of the pre-deploy tasks. I'll catch up with you in slack if I see you're available.

**Comment by bridgetkromhout** [comment]
It might be useful to document "how to run a local environment in a way that mimics what actually happens in the build". We don't have it all happen locally by default because it requires tools people might not have installed, and it takes too long for interactive use.

**Comment by mattstratton** [comment]
You can do that, but you won’t get it in hugo watch. You’ll only end up with generated html.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
