### ISSUE TITLE
Program should support links to slides and video

### ISSUE THREAD

**Issue by aaronblythe** [devopsdays/devopsdays-theme#600]
In 2016 when we finished we provided links at directly on the program page:

https://www.devopsdays.org/events/2016-kansascity/program/

Note the "(slides) (video)" for each talk.

Now that we can add the markdown for embedding slides and video to the specific page for the speaker/talk. It would be nice to also be able to provide these links for the yaml for the program.

**Comment by aaronblythe** [comment]
Since there is no embedding trickery, I think this could be as simple as using `video` and `slides` in the data/events/year-city.yml.

Then the update to themes/devopsdays-theme/layouts/program/single.html would simply need this in the section for `{{- else if or (eq .type "talk") (eq .type "workshop") -}}` and `{{- else if eq .type "ignite" -}}`

````
                              {{- if .video -}}
                              {{- if ne .video "" -}}
                                <a href="{{ (printf "%s" .video) }}"> (video) </a>
                              {{- end -}}
                              {{- end -}}
                              {{- if .slides -}}
                              {{- if ne .slides "" -}}
                                <a href="{{ (printf "%s" .slides) }}"> (slides) </a>
                              {{- end -}}
                              {{- end -}} 
````

**Comment by aaronblythe** [comment]
https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/program/single.html does not seem like it is in sync with https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/layouts/program/single.html 

So I will likely check in over on the `devopsdays-web` project.

**Comment by aaronblythe** [comment]
hrmm... maybe they are more in sync than I originally thought. I will update here.

**Comment by mattstratton** [comment]
Rather than adding yet another data field, I think we can just detect to see if the talk/ignite has something set for video or slide fields and then display the link. 

I’m on thumbs right now and going to bed, but I can work on it tomorrow night. I would prefer to avoid adding more configuration when we already have the info available.

**Comment by mattstratton** [comment]
I’m assuming that the links to “video”, etc will go to the talk page and not to the YouTube/speakerdeck, etc page.

**Comment by mattstratton** [comment]
And finally, if you want to compare/contrast, always check the version of the theme in the toml file at the root of the theme. I cut a release of the theme not too long ago but I’m pretty sure it was when we were having hiccups with making changes to devopsdays-web so I never pushed it.

**Comment by aaronblythe** [comment]
Makes sense, I originally tried to get the links from the individual speaker page. I assume that is how the title is scraped? Is that what `{{ $.Scratch.Get .title }}` is doing?

The way I have this now, the link is to leave the site and go to YouTube/Vimeo/Slideshare/Speakerdeck/etc. Are you saying you would prefer that they go to the page that the `speaker - title` links to?  I am fine with that, then this really just becomes a marker that video/slides are on that page, so... maybe an image for "video" and "slides" would be appropriate?

**Comment by mattstratton** [comment]
My issue with the offsite link is that a talk could have more than one slide link - I don’t want to be opinionated about where they go. 

Although linking back to the talk page is what it already does anyway. 

I just really, really don’t want to add even more configuration data. I guess I’m not 100% convonved that users wont click on the talk name to find the videos/slides. Maybe we just add a little badge next to the ones that have something in the video or slide frontmatter so it’s known they exist ... which is what I think you meant by the ‘image’.

**Comment by aaronblythe** [comment]
I think we are in agreement that (correct me if I am wrong):

- No new attributes, so we will read the YouTube/Vimeo/Slideshare/Speakerdeck/etc. from the individual program page
  -  If the YouTube/Vimeo setting are there (and not empty) then show a "video camera" icon
  -  If the Slideshare/Speakerdeck setting are there (and not empty) then show a "slideshow" icon
- In all cases this will just link to the page as the "speaker - title" already does.

I am willing to do this work over the next couple days.

What I need is some assistance on is how to read the YouTube/Vimeo/Slideshare/Speakerdeck/etc. from the individual program page.  From above, that is what my question of how is the title being pulled? If I understand this, I think I can take a swing at the rest.

**Comment by mattstratton** [comment]
Take a look at this section:
https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/program/single.html#L87-L91

```
{{ $.Scratch.Get (printf "%s-speaker" .title) }}
 -
 {{ $.Scratch.Get .title }}
```

Basically, inside of there and that section, you can us `$.Scratch.Get .VALUE` to get the value of anything. 

So for example, you should be able to get the youtube value with `$.Scratch.Get .youtube`

**Comment by aaronblythe** [comment]
I am confused... wouldn't the "opt-in" option to be filling out the `video` and `slides` on the data/events page like I have it?  If these are not filled out then there is nothing extra on the screen. If there is an opt-in the there would be need to be another configuration object even if it is simply some binary flag.  My understanding is that any other configuration is really, really not wanted.

I am not certain what users would do once they navigate to the site. We would need to see analytic data to determine that. I would rather not speculate.

What I do know is that as someone who is asked how to get to the videos, last year I always gave the devopsdays.org site for the KC program since the links were there. If the links are not on the program (or some representation that the videos can easily be found), then I will just give out our youtube link to our channel or playlists. I am fine with this, however I am willing to work together on a solution that is configurable for those that want this functionality and those that don't.

Given the current state, my communication to the attendees and our community that I will send out in the next day or two will be the youtube links instead of the devopsdays program page.

**Comment by mattstratton** [comment]
You also can edit the content on the program page right now in your markdown to say CLICK ON A TALK NAME TO SEE SLIDES AND VIDEO” as a workaround.

**Comment by mattstratton** [comment]
And I should totally add some google tag tracking on links to slideshare, YouTube, etc from the talk pages to see what the engagement is like. But that’s forward going.

**Comment by mattstratton** [comment]
I also am planning on trying to knock this out later this evening.
