### ISSUE TITLE
Migrate release scripts to use gump

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#604]
The release scripts are a little complicated right now. I've been using [gump](https://github.com/mh-cbon/gump) for version bumping/releasing via tags on some other projects, and I think that we could have better success using that.

**Comment by mattstratton** [comment]
Another possible options instead of `gump` is https://github.com/tj/git-extras/blob/master/Commands.md#git-release

It all just depends on what we want someone to have to install :)

**Comment by bridgetkromhout** [comment]
I am in favor of "as simple as possible" (and this is doubtless unsurprising).

**Comment by mattstratton** [comment]
This is not really needed and I'm going to close it.
