### ISSUE TITLE
Change mobile event menu from icons to collapsed menu

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#607]
Currently, when on mobile, in an event page the navigation uses icons. This makes it challenging for people to figure out where to click.

I previously tried to have two collapsing menus (the global nav and the event nav) but the event nav never seemed to be able to collapse. We need to figure out how to fix this.

**Comment by bridgetkromhout** [comment]
Could a quick-and-dirty option be "use icons that are (or include) screenshots of words?" (I realize that doesn't handle non-english well.)

**Comment by mattstratton** [comment]
At that point, we might as well just put in words - the reason for the collapsing menu is that on the small screen it doesn't fit. I can try to just put in words and see how that looks. 

The fix is here, basically...it just is going to take a little bit of tweaking:

https://stackoverflow.com/questions/42417018/bootstrap-4-multiple-fixed-top-navbars
