### ISSUE TITLE
Allow URL link on "custom" program type

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#611]
When creating a program item of type "custom", there should be a sub-element of "custom_url" which can link somewhere else.

Actually, this should work on all types, in case somebody wants to link elsewhere for reasons.

**Comment by mattstratton** [comment]
Also would be nice for open space type to allow linking to open space schedules

**Comment by technovangelist** [comment]
linking to somewhere else would be nice. It would be great to be able to set names of program items to something like slot1, and then the markdown doc can be called slot1.md, but have a slug in the frontmatter of "cool talk name" or 'speaker name' instead.

**Comment by chriscoffee** [comment]
@technovangelist:
 > It would be great to be able to set names of talk items to something like slot1, and then the markdown doc for the talk can be called slot1.md, but have a slug in the frontmatter of "cool talk name" or 'speaker name' instead.

Would you be able to expand on this behaviour slightly? I'm struggling to understand what you mean sorry!

Do you mean, you'd create a talk in /content/events/[event]/program/slot1.md which would generate a slug generated from a specific field and/or speaker name?

**Comment by mattstratton** [comment]
I'm not sure I want to mess with the naming of the files; it creates additional complexity.

I would suggest we could do this where if there is the presence of a "talk-title" element in the frontmatter it displays that instead. The default behavior needs to remain as it is, but we could enhance it as opt-in.
