### ISSUE TITLE
Shortcodes not compatible with hugo 0.32

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#618]
### Expected behavior

Build will pass appveyor's checks.

### Actual behavior

Build started breaking in https://github.com/devopsdays/devopsdays-web/pull/3782. 

### Reproduction Steps

@scottsbaldwin noticed that appveyor is using a newer hugo. Upgrade local hugo to 0.32.2 to see the failure. It works at 0.32.1.

Production isn't broken because netlify is currently pinned at hugo 0.30.2: https://github.com/devopsdays/devopsdays-web/blob/master/netlify.toml#L10

(Maybe we can't pin the version for appveyor?)

Before we upgrade hugo on netlify, we should fix this issue. You can see it in https://ci.appveyor.com/project/DevOpsDays/devopsdays-web/build/1.0.5186 

All the shortcodes seem to have this problem:

ERROR 2018/01/05 17:17:09 error processing shortcode "theme/shortcodes/email_proposals.html" for page "events\\2017-cape-town\\propose.md": template: theme/shortcodes/email_proposals.html:1:11: executing "theme/shortcodes/email_proposals.html" at <index $.Site.Data.ev...>: error calling index: value is nil; should be of type string

**Comment by bridgetkromhout** [comment]
The last appveyor build on hugo v0.31.1: https://ci.appveyor.com/project/DevOpsDays/devopsdays-web/build/1.0.5178
The first breaking appveyor build on hugo v0.32.2: https://ci.appveyor.com/project/DevOpsDays/devopsdays-web/build/1.0.5179

**Comment by bridgetkromhout** [comment]
The problem is likely introduced in here: https://github.com/gohugoio/hugo/compare/release-0.32.1...release-0.32.2

**Comment by bridgetkromhout** [comment]
An older issue, but might be similar: https://discourse.gohugo.io/t/error-calling-index-value-is-nil-should-be-of-type-string-in-theme--default-li-html/4516/3

**Comment by mattstratton** [comment]
This might be windows only. I have upgraded to latest hugo on my macbook and I can build the site (at least I can build the examplesite):

```
                   |  EN
+------------------+------+
  Pages            | 2211
  Paginator pages  |    2
  Non-page files   |   48
  Static files     | 5087
  Processed images |    0
  Aliases          |  224
  Sitemaps         |    1
  Cleaned          |    0

Total in 19123 ms
 ~  src  …  devopsdays  devopsdays-theme  exampleSite  fix-hugo-version  255  %  hugo version                                                                                                                                                                                                                                                                                                                                                                                         [16:36:04]
Hugo Static Site Generator v0.32.2 darwin/amd64 BuildDate: 2018-01-05T16:35:01-06:00
```

**Comment by mattstratton** [comment]
Production site builds fine on 0.32.2 darwin...

**Comment by mattstratton** [comment]
I stand corrected. It is failing in darwin; just the error is muted and it won't throw a message at the end. Carry on.

**Comment by mattstratton** [comment]
oof. Digging in, this could be pretty large. v0.32 is a breaking change in a lot of ways, and there are actually some really nice features of it (including something called Resources, which might allow us to remove the `gulp` tasks and put image handling in the hugo site generation itself).

My suggestion for now is to revert to 0.31 - I'll see if I can figure out how to do that with the appveyor script, and take on a larger initiative to update for 0.32 properly.

**Comment by mattstratton** [comment]
This is really odd. It's definitely something related to data - for example, Riga doesn't fail, but NYC does.

**Comment by mattstratton** [comment]
Denver seems to be the only other one that works. I'm trying to see what is different - it's something to do with the data and how it gets read.

**Comment by mattstratton** [comment]
Aha. It's not the data. It's the use of `index.md` instead of `welcome.md`.

With newer versions of hugo, `index` means something different. 

so what we need to do is rename all of the "index.md" files in event directories to `welcome.md` and also update the alias (right now they are aliased to `welcome`, but the alias needs to just be to the root, etc)

This will get fixed in the devopsdays-web repo in both the content folders and the examples.

**Comment by mattstratton** [comment]
Fixed in https://github.com/devopsdays/devopsdays-web/pull/3980
