### ISSUE TITLE
Allow event_links to pull arbitrary event data

### ISSUE THREAD

**Issue by tylermauthe** [devopsdays/devopsdays-theme#623]
Hugo only allows access of site data inside a content page by way of a shortcode. Currently, `event_link` allows you to create links to sub-pages based on the event name. I propose we extend this to allow pulling arbitrary event data for either the URL or text portion of the `a` tag.

Current interface for `event_link`:
`{{< event_link page="location" text="Getting here" >}}`

New interface for `event_link`:
`{{<event_link url-key="registration_link" text-key="location_address" >}}`
`{{<event_link page="location" text="Getting here" >}}`
`{{<event_link url-key="registration_link" text="Register Now!" >}}`
`{{<event_link page="location" text-key="location_address" >}}`

If both `url-key` and `page` are specified, `url-key` will override `page`. Similarly for `text-key` and `text`, `text-key` takes precedence.

**Comment by mattstratton** [comment]
Fixed in #617
