### ISSUE TITLE
Remove dependency on "welcome.md"

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#63]
This path is a dependency from the old Webby site. New events don't require it and we can/should make sure we aren't looking for it in any code.

**Comment by bridgetkromhout** [comment]
I'm confused here because webby didn't use "welcome.md".

**Comment by mattstratton** [comment]
No, it didn't, but with how we did the migration there was a reason. I don't recall what it was, but it's not important why I guess :)

**Comment by mattstratton** [comment]
Related to #59

**Comment by mattstratton** [comment]
I am pretty sure this is handled, as the new `index.md` files are supposed to alias to `/welcome` so anything that points to it will work.
