### ISSUE TITLE
Create search feature

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#633]
Reference - https://discourse.gohugo.io/t/how-to-hugo-search-lunr-gulp/13342

**Comment by chriscoffee** [comment]
This looks like a duplicate of #347.

Personally I think going with algolia like you suggested is the correct option. They have 'free' for open source https://www.algolia.com/for-open-source

Here's some documentation on Netlify's implementation moving from lunr to algolia https://www.netlify.com/blog/2017/10/10/replacing-our-search-with-algolia/ which should be helpful.

**Comment by mattstratton** [comment]
Oh yeah. It's a duplicate. I'm a dummy :)
