### ISSUE TITLE
Add improvements for gulp tasks

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#649]
The plugin we use for retina images (the html modifications) is pretty much not maintained.

I suggest we update to use a combination of the following:

https://github.com/Tsuguya/posthtml-sugar-srcset
https://www.npmjs.com/package/gulp-srcset
https://www.npmjs.com/package/gulp-html-srcset

This also likely allows us to only do retina images on the images we require; this can help us remove the "additional images" processing, which will shave off about 1 minute from production builds.

**Comment by bridgetkromhout** [comment]
Sounds awesome! I am in favor of shorter builds. Thanks.

**Comment by mattstratton** [comment]
Duplicate of #507
