### ISSUE TITLE
Speakers show up on speaker page even if they don't have a talk

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#66]
This is probably an edge case that will never happen (why would you create the speaker file without having a talk file?) but it might not be a bad idea to fix it anyway.

**Comment by mattstratton** [comment]
Is this an actual problem? What do you think, @bridgetkromhout ?

**Comment by bridgetkromhout** [comment]
I'd file this under "doctor, it hurts when I do this"/"so stop doing it". If the speaker is showing up with no talk file, then good. maybe it will motivate the creation of said talk file.

**Comment by mattstratton** [comment]
It's also a possible "feature", as in, maybe they have their list of speakers already, but haven't posted up the associated talks. That's not a bad thing. I'm gonna close this as wontfix.
