### ISSUE TITLE
single-day events displaying incorrectly on welcome page

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#663]
As reported by @robscott in https://github.com/devopsdays/devopsdays-web/issues/5565, single-day events are displaying incorrectly. I have a correction pending for this regression.

**Comment by bridgetkromhout** [comment]
Part of the build timed out, but you can see it in action in the branch deploy that didn't time out: https://fix-dates-welcome-page--devopsdays-theme.netlify.com/events/2018-paris/welcome/ 

<img width="315" alt="screen shot 2018-10-06 at 6 17 24 pm" src="https://user-images.githubusercontent.com/2104453/46576284-1d606700-c994-11e8-9e4e-259d39cd8061.png">

contrasted with what's live in production before the fix is available: https://www.devopsdays.org/events/2018-paris/welcome/

<img width="314" alt="screen shot 2018-10-06 at 6 17 04 pm" src="https://user-images.githubusercontent.com/2104453/46576291-2c471980-c994-11e8-9765-fc7429eb7224.png">

**Comment by mattstratton** [comment]
Huh. This used to work.

**Comment by bridgetkromhout** [comment]
> Huh. This used to work.

Right. I think this is a regression caused by the datetime cleanup work. Is there anything else you'd like done here? I'd like to get this fix into production.
