### ISSUE TITLE
Add "Deploys by Netlify" badge to footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#669]
Per Netlify, in order for devopsdays.org to continue being hosted for free, we will need to add a badge for Netlify to the site (this is due to the high amount of bandwidth we are using). 

Code will look like this:

```
<a href="https://www.netlify.com">
  <img src="https://www.netlify.com/img/global/badges/netlify-light.svg"/>
</a>
```

Note - while normally I would recommend we self-host the image, given the bandwidth issue, we might as well use Netlify's origin instead of our own :)

**Comment by bridgetkromhout** [comment]
> while normally I would recommend we self-host the image, given the bandwidth issue, we might as well use Netlify's origin instead of our own

This is a tiny image, though. And I really don't like the idea of something not controlled by us being displayed on the front page. Not that I think they'd change the picture on us, but always in motion is the future.

Also, I'd prefer a transparent background:

<img width="293" alt="screen shot 2018-11-03 at 9 39 06 am" src="https://user-images.githubusercontent.com/2104453/47953498-9085da80-df4c-11e8-9dcf-ef47c33af20b.png">

The link itself is fine, as is the placement (it's in a good place for it).

**Comment by mattstratton** [comment]
I updated https://github.com/devopsdays/devopsdays-theme/pull/670 to now host the image from our own site instead of Netlify. As I mentioned, we need to use one of their badges; the light one (see the Press link above) seemed the least obtrusive.
