### ISSUE TITLE
[Enhancement] Allow for custom sponsor sign up links

### ISSUE THREAD

**Issue by jaumann** [devopsdays/devopsdays-theme#680]
Currently, we hard-code the "BECOME A XXX SPONSOR!" links to point back to sponsor.md. It would be nice if we could override this to a custom landing page to allow for sponsor signups. For example, in Baltimore 2019 we are using this link to register sponsors: https://devopsdaysbaltimore2019.busyconf.com/bookings/new?discount=SPONSOR

**Comment by mattstratton** [comment]
With the change I am putting in place, it would add a `sponsor_link` field to the event YAML file, which them overrides both the "become a x sponsor" links, and also sets the destination for the "sponsor" nav item. Is that what you're looking for?

**Comment by jaumann** [comment]
Thats for the most part what I was looking for, but I like the idea of still being able to go to the sponsor nav as a general landing page if possible

**Comment by mattstratton** [comment]
I modified the PR so that setting `sponsor_link` only affects the "become an XXX sponsor!" links.

**Comment by mattstratton** [comment]
@jaumann this change was pushed to the production site, so you can use it now if you'd like.
