### ISSUE TITLE
Look into replacing TravisCI

### ISSUE THREAD

**Issue by chriscoffee** [devopsdays/devopsdays-theme#686]
Travis CI was recently acquired and then has laid off some of its employees.

* https://techcrunch.com/2019/01/23/idera-acquires-travis-ci/
* https://twitter.com/rakyll/status/1098675047416311808
* https://twitter.com/EricaJoy/status/1098595526742814722

This could mean that we can't use Travis anymore.

We could possibly use one of the following replacements: GitHub Actions, Azure Pipelines, CircleCI

**Comment by bridgetkromhout** [comment]
Thanks. We already moved the `devopsdays-web` repo builds to CircleCI. The theme will be a little more work, but it's on our radar.

**Comment by chriscoffee** [comment]
Awesome, thanks @bridgetkromhout! I'll close this now 👍
