### ISSUE TITLE
Image tag left blank is not displaying default microphone image

### ISSUE THREAD

**Issue by MikeRosTX** [devopsdays/devopsdays-theme#689]
It was discovered in #6465 that leaving the tag **_image = ""_** blank it doesn't set the default microphone image. The tag actually has to be deleted for the default image to appear.

**Comment by bridgetkromhout** [comment]
I tried https://help.github.com/en/articles/transferring-an-issue-to-another-repository in this case.

**Comment by mattstratton** [comment]
Fixed in 26f834909ff0343869acc7341767c9818b587d3f
