### ISSUE TITLE
Clean up display of events that span months

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#71]
Test for display on both left nav and homepage

**Comment by mattstratton** [comment]
At present, it's not handled for. So we have to decide how we want to deal with it.

This shows a couple different ideas on how to display (in the left nav; I think for the homepage it's easier)

![untitled-2___100___layer_3__rgb_8___](https://cloud.githubusercontent.com/assets/1280666/21743556/1e6ce3fa-d4ca-11e6-8798-881a6638eb9d.png)

**Comment by bridgetkromhout** [comment]
As we discussed, my order of preference is center, then right, then left.
