### ISSUE TITLE
Create sponsor info page

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-theme#74]
There is quite a bit of information requested by sponsors. This page would be a place to share that. 

For example:

- When is set up and tear down?
- Is shipping available to the venue?
- Is shipping available from the venue?
- Who should sponsors send?
- Is there an A/V vendor? Who is it and how do they contact them?
- Is there WiFi?
- Is there electricity? How much? Is it included in the price?

The changes would be:

1. Add a new page called sponsor-info.md created from the new event script
2. Add a commented out link in sponsor.md to the new file

(FYI, I'm going to create one for Seattle in the existing template and will link it here when done so people can see more about what i mean)

**Comment by bridgetkromhout** [comment]
Sponsors definitely need this info; good call! We need to be careful about implying any defaults since of course they vary so widely.

**Comment by mattstratton** [comment]
Based upon discussing with Bridget, we are thinking adding this as a commented-out table of stuff with this list at the bottom of the `sponsor.md` template will be a more direct way.

**Comment by bridgetkromhout** [comment]
Hi, @kmugrage - here's an MVP for this: https://github.com/devopsdays/devopsdays-web/pull/1687

Please take a look and let us know if this is the kind of starting prompt you were imagining.

**Comment by bridgetkromhout** [comment]
(I merged my PR but we can add to it.)

**Comment by mattstratton** [comment]
@bridgetkromhout can this be closed?

**Comment by kmugrage** [comment]
Looks good to me as an MVP, thanks for doing it! Can always create a new request for modifications if you'd like to close it.

**Comment by bridgetkromhout** [comment]
Yes, thanks, @mattstratton - looks like it's a good start for @kmugrage and we can keep adding to it as we go.
