### ISSUE TITLE
Create default event homepage images

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#81]
~The idea is to find a bunch of existing, free-use images for cities/locations we know exist, and create them in the homepage sizing. So people can choose from them instead of defaulting to the brain if they want to.~

NEW PLAN - generate a default logo-square.png during the make new event, and if not, it bails to the Brain logo the way it does now.

**Comment by bridgetkromhout** [comment]
Let's go with this: https://twitter.com/devopsdaysmsp/profile_image?size=original

**Comment by mattstratton** [comment]
We should check to see if this can go into an `<img>` tag.

So in the make new event, if they provide a twitter handle, we will curl it down and pop it into the right place `/static/events/YYYY-CITY/logo-square.png`.

They can over-ride it by replacing `logo-square.png`.

If they don't provide a twitter handle, then make new event will put in the brain default.

**Comment by mattstratton** [comment]
Did some more thinking on this - we don't know the format of the image you might get from twitter, so here's some thoughts:

1. create new event script will call their twitter image and dump it in the directory. It will set the homepage-image parameter in their data file to that name of the image (note: the parameter name might be wrong)
2. The homepage will now just render the file set in the data file on the grid; if it's not set, it will show the brain.

**Comment by mattstratton** [comment]
Fixed in 608ccb1f6d7a3784d4f56a971bb6a75cb07b4032
